Repository Laravel-Backpack/CRUD, pull requests merged in 2018-07, with the labels that each got.

#1499 [Bug fix] datatables trigger responsive when colvis toggled
  src/resources/views/inc/datatables_logic.blade.php
Labels: bug, ready

#1507 [Feature][3.4][Ready] Actions (way to get the controller method being called)
  src/CrudPanel.php
Labels: feature, minor change, non breaking change, ready

#1564 add button data to include for button subview
  src/resources/views/inc/button_stack.blade.php
Labels: feature, non breaking change, ready
