Repository Laravel-Backpack/CRUD, pull requests merged in 2018-04, with the labels that each got.

#1338 Apply fixes from StyleCI
  src/PanelTraits/Read.php
Labels: working on it

#1330 Fix #1321
  src/ModelTraits/SpatieTranslatable/HasTranslations.php
Labels: bug, ready, urgent

#1339 [Ready] Get the correct current ID for nested resources
  CHANGELOG.md
  src/PanelTraits/Read.php
  src/app/Http/Controllers/CrudController.php
  src/app/Http/Controllers/CrudFeatures/Revisions.php
  src/app/Http/Controllers/CrudFeatures/ShowDetailsRow.php
Labels: ready

#1343 Hide "Remove Filters" when not selected
  src/resources/views/inc/filters_navbar.blade.php
Labels: working on it

#1352 Apply fixes from StyleCI
  src/PanelTraits/Fields.php
Labels: working on it

#1354 Apply fixes from StyleCI
  src/PanelTraits/Filters.php
Labels: working on it
