Repository Laravel-Backpack/CRUD, pull requests merged in 2018-02, with the labels that each got.

#1232 Apply fixes from StyleCI
  src/PanelTraits/AutoSet.php
Labels: working on it

#1227 Issue 643 reoccurred
  src/resources/views/list.blade.php
  src/resources/views/show.blade.php
Labels: ready

#1129 switch to Illuminate\Http\Request in CrudController
  src/app/Http/Controllers/CrudController.php
Labels: ready

#1236 Apply fixes from StyleCI
  src/app/Http/Controllers/CrudController.php
Labels: working on it

#1233 Added setLabeller method for customizing how labels are made
  CHANGELOG.md
  src/PanelTraits/AutoSet.php
Labels: feature, ready, testing or needs confirmation, working on it

#1246 fixed orderBy in ajax datatables
  src/app/Http/Controllers/CrudFeatures/AjaxTable.php
Labels: working on it

#1248 Apply fixes from StyleCI
  src/app/Http/Controllers/CrudFeatures/SaveActions.php
Labels: working on it

#1168 Allows setting a default value for select2_from_array field
  src/resources/views/fields/select2_from_array.blade.php
Labels: working on it

#444 alter image field so a broken image is not displayed on a new entry
  src/resources/views/fields/image.blade.php
Labels: stale

#640 Adding 'disk' option for image field
  src/resources/views/fields/image.blade.php
Labels: stale
