Repository Laravel-Backpack/CRUD, pull requests merged in 2018-11, with the labels that each got.

#1540 Maybe fixes #1539
  src/resources/views/inc/field_wrapper_attributes.blade.php
Labels: bug

#1658 [Feature][3.5][Ready] Fix access to $crud in button from model function
  src/resources/views/inc/button_stack.blade.php
Labels: breaking change, ready

#1693 tr lang added
  src/resources/lang/tr/crud.php
Labels: needs-more-info

#656 Update AutoSet.php
  src/PanelTraits/AutoSet.php
Labels: bug

#1484 [3.4][Feature][Ready] Select2_from_ajax can depend on any other input
  src/resources/views/fields/select2_from_ajax.blade.php
  src/resources/views/fields/select2_from_ajax_multiple.blade.php
Labels: feature, minor change, non breaking change
