Repository Laravel-Backpack/CRUD, pull requests merged in 2018-05, with the labels that each got.

#1358 Updated LV language translation
  src/resources/lang/lv/crud.php
Labels: needs-more-info, working on it

#1368 Update crud.php
  src/resources/lang/pt_br/crud.php
Labels: working on it

#1383 Allow dot notation text fields, which enables relationship information
  src/resources/views/columns/text.blade.php
Labels: minor change

#1392 Made the check column type exportable
  src/resources/views/columns/check.blade.php
Labels: bug, feature, minor change, non breaking change

#1387 [EH] add possibility to use custom fields
  src/resources/views/inc/show_fields.blade.php
Labels: non breaking change, ready

#1388 [EH] add possibility to use custom columns
  src/PanelTraits/Search.php
Labels: non breaking change, ready

#1389 [EH] add possibility to use custom filters
  src/PanelTraits/Filters.php
Labels: non breaking change, ready

#1432 Apply fixes from StyleCI
  src/public/ckeditor/samples/old/sample_posteddata.php
Labels: working on it
