Repository Laravel-Backpack/CRUD, pull requests merged in 2018-03, with the labels that each got.

#1277 Apply fixes from StyleCI
  src/app/Console/Commands/Install.php
Labels: working on it

#1280 Apply fixes from StyleCI
  src/app/Console/Commands/Install.php
Labels: working on it

#679 Save action access
  src/app/Http/Controllers/CrudFeatures/SaveActions.php
Labels: bug, ready

#1289 Added missing fields, some minor changes to the translation
  src/resources/lang/ro/crud.php
Labels: working on it

#1287 [Feature] Added "view" column and filter
  CHANGELOG.md
  src/resources/views/columns/view.blade.php
  src/resources/views/filters/view.blade.php
Labels: working on it

#1295 AdminLTE update
  src/resources/views/fields/browse_multiple.blade.php
  src/resources/views/fields/date_picker.blade.php
  src/resources/views/fields/date_range.blade.php
  src/resources/views/fields/datetime_picker.blade.php
  src/resources/views/fields/select2.blade.php
  src/resources/views/fields/select2_from_ajax.blade.php
  src/resources/views/fields/select2_from_ajax_multiple.blade.php
  src/resources/views/fields/select2_from_array.blade.php
  src/resources/views/fields/select2_multiple.blade.php
  src/resources/views/filters/date.blade.php
Labels: working on it

#1279 [Feature][3.4][Merged] removed dependency loading
  src/CrudServiceProvider.php
Labels: ready

#1310 fix ckeditor browser server button missing problem
  src/resources/views/fields/ckeditor.blade.php
Labels: working on it
