Repository Laravel-Backpack/CRUD, pull requests merged in 2019-11, with the labels that each got.

#2185 fix stackoverflow link
  CONTRIBUTING.md
Labels: needs-more-info

#2174 [4.0][Ready] Added config for stripping the request using EXCEPT or ONLY
  src/app/Library/CrudPanel/Traits/Fields.php
  src/config/backpack/crud.php
Labels: feature

#2196 4.0 [BUG] Fix for orderByRaw and inRandomOrder in orderLogic.
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: ready

#2260 [4.0][HOTFIX] Image field wrong init function name
  src/resources/views/crud/fields/image.blade.php
Labels: needs-more-info
