Repository Laravel-Backpack/CRUD, pull requests merged in 2020-02, with the labels that each got.

#2426 [4.0][BUGFIX] select2_from_ajax send empty value for clear
  src/resources/views/crud/fields/select2_from_ajax.blade.php
Labels: Bug, Priority: MUST

#2438 [4.0][BUGFIX] Define fqn for Exception.
  src/app/Models/Traits/CrudTrait.php
Labels: needs-more-info

#2458 [4.0][WIP] Code Quality Improvements
  src/app/Models/Traits/CrudTrait.php
Labels: Priority: SHOULD, non breaking change
