Repository Laravel-Backpack/CRUD, pull requests merged in 2020-09, with the labels that each got.

#3177 [Bug fix] Filters not clearing properly when a select2_ajax filter is used
  src/resources/views/crud/inc/filters_navbar.blade.php
Labels: Bug, Priority: MUST

#3182 Fix filter fallback doesn't work issue
  src/app/Library/CrudPanel/CrudFilter.php
Labels: Bug, Priority: MUST

#3189 Add support for Laravel 8
  composer.json
Labels: Priority: MUST, dependencies

#3192 Bugfix values function
  src/app/Library/CrudPanel/CrudFilter.php
Labels: Bug, Priority: MUST

#3203 Fix List operation bulk buttons on XS and SM
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Read.php
  src/public/packages/backpack/crud/css/list.css
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/inc/export_buttons.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
Labels: Bug, Priority: MUST

#3202 [4.1] fix upload multiple column
  src/resources/views/crud/columns/upload_multiple.blade.php
Labels: Bug, Priority: MUST

#3208 Fix recover password title
  src/app/Http/Controllers/Auth/ForgotPasswordController.php
Labels: Bug

#3207 Fix recover password in Laravel 8
  src/app/Library/Auth/PasswordBroker.php
Labels: Bug

#3221 Update form_content.blade.php
  src/resources/views/crud/form_content.blade.php
Labels: Possible Bug

#3226 [Bug fix][4.2] Fix init value for browse_multiple field when multiple is true
  src/resources/views/crud/fields/browse_multiple.blade.php
Labels: Minor Bug
