Repository Laravel-Backpack/CRUD, pull requests merged in 2020-07, with the labels that each got.

#2851 added guzzlehttp 7.0 support
  composer.json
Labels: Priority: SHOULD, needs-more-info

#2809 [4.1] Fix nested relations on select column
  src/app/Library/CrudPanel/CrudPanel.php
Labels: Bug

#2971 fix: does not look for relationship if field entinty = false
  src/app/Library/CrudPanel/Traits/Fields.php
Labels: Priority: MUST

#2974 [4.1][Bug fix] enum field could not be added using fluent syntax
  src/app/Library/CrudPanel/Traits/AutoSet.php
Labels: Bug, Priority: MUST

#3008 [Feature] Add new item label to repeatable field
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Feature

#3005 Fix for #3000 - Undefined index: pivot on modifyField
  src/app/Library/CrudPanel/Traits/Create.php
Labels: Bug

#3014 [4.X] Fix group by in list operation
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: Bug

#3046 fix typo
  src/resources/lang/it/crud.php
Labels: needs-more-info

#3033 Allow multiple page_or_link
  src/resources/views/crud/fields/page_or_link.blade.php
Labels: Priority: SHOULD

#3070 Remove hide class from image field type
  src/resources/views/crud/fields/image.blade.php
Labels: Minor Bug
