Repository Laravel-Backpack/CRUD, pull requests merged in 2020-12, with the labels that each got.

#3351 Make compatible with UUIDs
  src/resources/views/crud/fields/checklist.blade.php
Labels: Bug

#3355 Removed duplicate semicolon and added required space
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Priority: COULD

#3259 [4.1] Fix order by applied when in mongo db
  src/app/Http/Controllers/Operations/ListOperation.php
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/AutoSet.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Query.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/app/Models/Traits/HasRelationshipFields.php
Labels: Bug, Priority: MUST

#3276 [bug fix] allow models with arrayed names to be translated.
  src/resources/views/crud/fields/inc/translatable_icon.blade.php
Labels: Bug, Priority: SHOULD

#3327 Fix for translatable icon inside a multi input fields
  src/resources/views/crud/fields/checklist_dependency.blade.php
Labels: Bug

#3340 Adopt The Whole Fruit Manifesto
  CONTRIBUTING.md
  README.md
Labels: Priority: SHOULD

#3357 Fix for elements on long dropdowns being cut off
  src/public/packages/backpack/crud/css/list.css
Labels: Minor Bug

#3377 Fix for when checklist value is empty
  src/resources/views/crud/fields/checklist.blade.php
Labels: Bug, Priority: MUST

#3379 Refactor delete
  src/resources/views/crud/buttons/delete.blade.php
Labels: Priority: COULD, non breaking change, refactoring

#3369 Allow fluent filters to use options() and values() interchangeably
  src/app/Library/CrudPanel/CrudFilter.php
Labels: Feature, Priority: SHOULD, non breaking change

#3404 fix the JS error when clicking the Delete button inside the Show oper…
  src/resources/views/crud/buttons/delete.blade.php
Labels: Bug, Priority: MUST

#3408 Change redirect route after logout
  src/app/Http/Controllers/Auth/LoginController.php
Labels: Minor Bug
