Repository Laravel-Backpack/CRUD, pull requests merged in 2020-08, with the labels that each got.

#3064 [4.1] Fix inline main modal fields inclusion
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
Labels: Bug

#3104 [4.1] Fixing save action order picking
  src/app/Library/CrudPanel/Traits/SaveActions.php
Labels: Bug

#3015 [4.X] Add table prefix to backpack orderBy clauses.
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: Priority: SHOULD, needs-more-info

#3114 Fix #3112 - bulk clone now uses translation strings for error/success messages
  src/resources/lang/en/crud.php
  src/resources/views/crud/buttons/bulk_clone.blade.php
Labels: Bug

#3116 [4.1] fix overwrite of field name in hasone relations
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: needs-more-info

#3126 Update HasRelationshipFields.php
  src/app/Models/Traits/HasRelationshipFields.php
Labels: Bug

#3125 [4.1] Fix for getting table name with prefix.
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: Bug

#3129 [Bug] CRUD entity could not include search string
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Bug

#3134 [4.X] Fix middleware inclusion if you want to override web with your own array.
  src/routes/backpack/custom.php
Labels: Possible Bug, Priority: COULD

#3069 Removes the camelCasing of filter names -
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/Traits/Filters.php
  src/resources/views/crud/filters/date.blade.php
  src/resources/views/crud/filters/date_range.blade.php
  src/resources/views/crud/filters/dropdown.blade.php
  src/resources/views/crud/filters/example.blade.php
  src/resources/views/crud/filters/range.blade.php
  src/resources/views/crud/filters/select2.blade.php
  src/resources/views/crud/filters/select2_ajax.blade.php
  src/resources/views/crud/filters/select2_multiple.blade.php
  src/resources/views/crud/filters/simple.blade.php
  src/resources/views/crud/filters/text.blade.php
Labels: Bug, Priority: MUST

#3151 Active class on topbar .app-header not header
  src/resources/views/base/inc/sidebar.blade.php
Labels: Priority: MUST

#3123 added name to fetch route
  src/app/Http/Controllers/Operations/FetchOperation.php
Labels: Priority: SHOULD

#3159 Bugfix "select2 grouped" not working
  src/resources/views/crud/fields/select2_grouped.blade.php
Labels: Bug, Priority: MUST

#3158 [Bug fix] allow the check column type to use the wrapper functionality
  src/resources/views/crud/columns/check.blade.php
Labels: Minor Bug

#3164 improve Serbian translation
  src/resources/lang/sr/base.php
Labels: needs-more-info
