Repository Laravel-Backpack/CRUD, pull requests merged in 2020-03, with the labels that each got.

#2487 Update ckeditor4.php
  src/resources/views-elfinder/ckeditor4.php
Labels: needs-more-info

#2488 Update filepicker.php
  src/resources/views-elfinder/filepicker.php
Labels: needs-more-info

#2486 Update tinymce.php
  src/resources/views-elfinder/tinymce.php
Labels: needs-more-info

#2504 [4.0][Feature] Allow delay on AJAX calls for select2_from_ajax fields
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
Labels: Feature, Priority: COULD, non breaking change

#2457 [4.0][Feature] Implement orderButtons
  src/app/Library/CrudPanel/Traits/Buttons.php
  tests/Unit/CrudPanel/CrudPanelButtonsTest.php
Labels: Feature, Priority: MUST, non breaking change

#2477 [4.0][Feature][Ready] Delete operation can respond with Notification Bubbles
  src/resources/views/crud/buttons/bulk_delete.blade.php
  src/resources/views/crud/buttons/delete.blade.php
Labels: Feature, Priority: SHOULD, non breaking change

#2515 Actualisation of Russian localisation
  src/resources/lang/ru/base.php
  src/resources/lang/ru/crud.php
Labels: needs-more-info

#2520 [Bug] Fix php artisan backpack:version command
  src/app/Console/Commands/Version.php
Labels: Bug

#2526 [4.0] fix debug flag in installation command
  src/app/Console/Commands/Install.php
Labels: Bug

#2528 [4.0][BUGFIX] Elfinder publish command error
  src/app/Console/Commands/Install.php
Labels: needs-more-info

#2529 [4.0] [BUGFIX] Remove PUT route from createOperation
  src/app/Http/Controllers/Operations/CreateOperation.php
Labels: Bug

#2550 [4.1] Split CrudTrait into multiple smaller traits
  src/app/Models/Traits/CrudTrait.php
  src/app/Models/Traits/HasEnumFields.php
  src/app/Models/Traits/HasFakeFields.php
  src/app/Models/Traits/HasRelationshipFields.php
  src/app/Models/Traits/HasTranslatableFields.php
  src/app/Models/Traits/HasUploadFields.php
Labels: Priority: COULD, non breaking change, refactoring

#2476 [4.0][BUGFIX] fix switch icon_picker
  src/resources/views/crud/fields/icon_picker.blade.php
Labels: Bug

#2559 [4.0] Updates acorn dependency
  package-lock.json
Labels: Bug, dependencies

#2568 [4.1] Remove Laravel 5.8 Support
  .scrutinizer.yml
  .travis.yml
  composer.json
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
Labels: Priority: COULD, Priority: SHOULD, breaking change

#2584 [4.1] Remove intervention\image dependency
  composer.json
Labels: Priority: SHOULD, breaking change, refactoring

#2586 [4.1][Refactoring] Separated revisions operation
  src/app/Http/Controllers/Operations/RevisionsOperation.php
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/Views.php
  src/app/Library/CrudPanel/Traits/ViewsAndRestoresRevisions.php
  src/config/backpack/crud.php
  src/resources/lang/bg/crud.php
  src/resources/lang/cs/crud.php
  src/resources/lang/da-DK/crud.php
  src/resources/lang/da_DK/crud.php
  src/resources/lang/de/crud.php
  src/resources/lang/el/crud.php
  src/resources/lang/en/crud.php
  src/resources/lang/es/crud.php
  src/resources/lang/fa/crud.php
  src/resources/lang/fr-CA/crud.php
  src/resources/lang/fr/crud.php
  src/resources/lang/fr_CA/crud.php
  src/resources/lang/id/crud.php
  src/resources/lang/it/crud.php
  src/resources/lang/ja/crud.php
  src/resources/lang/lv/crud.php
  src/resources/lang/nl/crud.php
  src/resources/lang/pt-BR/crud.php
  src/resources/lang/pt/crud.php
  src/resources/lang/pt_br/crud.php
  src/resources/lang/ro/crud.php
  src/resources/lang/ru/crud.php
  src/resources/lang/tr/crud.php
  src/resources/lang/zh-Hant/crud.php
  src/resources/lang/zh-cn/crud.php
  src/resources/views/crud/buttons/revisions.blade.php
  src/resources/views/crud/inc/revision_timeline.blade.php
  src/resources/views/crud/revisions.blade.php
Labels: breaking change, refactoring

#2587 [4.1.0][Refactoring] Separate elFinder functionality into a first-party add-on
  src/BackpackServiceProvider.php
  src/app/Console/Commands/Install.php
  src/app/Console/Commands/Traits/PrettyCommandOutput.php
  src/config/elfinder.php
  src/resources/views-elfinder/ckeditor4.php
  src/resources/views-elfinder/elfinder.blade.php
  src/resources/views-elfinder/filepicker.php
  src/resources/views-elfinder/standalonepopup.php
  src/resources/views-elfinder/tinymce.php
  src/resources/views-elfinder/tinymce4.php
Labels: Priority: SHOULD, breaking change, refactoring

#2592 [4.0] Fix widget styles not loading
  src/resources/views/base/blank.blade.php
  src/resources/views/base/layouts/top_left.blade.php
  src/resources/views/base/my_account.blade.php
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
  src/resources/views/crud/revisions.blade.php
  src/resources/views/crud/show.blade.php
Labels: Bug, Priority: MUST

#2610 [4.1.0] Show operation adds a "Save and Preview" save action
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/resources/lang/en/crud.php
  src/resources/lang/es/crud.php
  src/resources/lang/fr/crud.php
  src/resources/lang/ro/crud.php
Labels: Feature, Priority: COULD, dependent, non breaking change

#2615 [4.1.0][Feature][Ready] Relationship & relationship_count columns
  src/resources/views/crud/columns/relationship.blade.php
  src/resources/views/crud/columns/relationship_count.blade.php
Labels: Feature, Priority: MUST, non breaking change
