Repository Laravel-Backpack/CRUD, pull requests merged in 2020-04, with the labels that each got.

#2627 Fix different date formats in Date Range Field
  src/resources/views/crud/fields/date_range.blade.php
Labels: Bug, Priority: MUST

#2599 [4.1.0] Fluent Syntax for Widgets
  src/app/Library/Widget.php
Labels: Priority: MUST, non breaking change

#2513 [4.1] Fluent syntax for Fields, Columns, Filters
  src/app/Http/Controllers/Operations/ListOperation.php
  src/app/Library/CrudPanel/CrudButton.php
  src/app/Library/CrudPanel/CrudColumn.php
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/Traits/AutoSet.php
  src/app/Library/CrudPanel/Traits/Buttons.php
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/Filters.php
  src/resources/views/crud/inc/button_stack.blade.php
  src/resources/views/crud/inc/filters_navbar.blade.php
  tests/Unit/CrudPanel/BaseCrudPanelTest.php
  tests/Unit/CrudPanel/CrudPanelButtonsTest.php
Labels: Feature, Priority: SHOULD, non breaking change

#2266 [4.1][Feature][Beta] Repeatable field type (aka matrix; aka group)
  src/resources/views/crud/fields/browse.blade.php
  src/resources/views/crud/fields/ckeditor.blade.php
  src/resources/views/crud/fields/date_picker.blade.php
  src/resources/views/crud/fields/date_range.blade.php
  src/resources/views/crud/fields/datetime_picker.blade.php
  src/resources/views/crud/fields/hidden.blade.php
  src/resources/views/crud/fields/icon_picker.blade.php
  src/resources/views/crud/fields/number.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/fields/select_and_order.blade.php
  src/resources/views/crud/fields/simplemde.blade.php
  src/resources/views/crud/fields/table.blade.php
  src/resources/views/crud/fields/text.blade.php
  src/resources/views/crud/fields/tinymce.blade.php
Labels: Feature, Priority: MUST, non breaking change

#2654 [4.1][Bug] re-order parentheses for relationship field options
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
Labels: Bug

#2400 [4.0][BUGFIX] Fixes #2397 - browse_multiple field
  src/resources/views/crud/fields/browse_multiple.blade.php
Labels: Bug, Priority: MUST

#2705 pameters not respecting what passed
  src/helpers.php
Labels: Bug

#2670 [4.1] [Fix] display translatable field in relationship
  src/app/Library/CrudPanel/CrudPanel.php
Labels: Bug

#2700 [4.1-beta][Bug] Browse multiple field with latest elfinder
  src/resources/views/crud/fields/browse_multiple.blade.php
Labels: Bug, Priority: MUST
