Repository Laravel-Backpack/CRUD, pull requests merged in 2020-06, with the labels that each got.

#2881 [4.1] Fix tab highlight.
  src/resources/views/crud/form_content.blade.php
Labels: Bug

#2802 Avoid space after commas
  src/resources/views/crud/columns/array.blade.php
  src/resources/views/crud/columns/multidimensional_array.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_from_array.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
Labels: Bug, Priority: SHOULD, non breaking change

#2888 Fixes [Bug] The wrapper argument for the chart widget is ignored #2887
  src/resources/views/base/widgets/chart.blade.php
Labels: needs-more-info

#2884 [4.1] Fixing FetchOperation behaviour when clauses are already applied.
  src/app/Http/Controllers/Operations/FetchOperation.php
Labels: Bug, non breaking change

#2872 [4.1] Fix filter naming/reference consistency, fix simple filter
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/Traits/Filters.php
  src/resources/views/crud/filters/date.blade.php
  src/resources/views/crud/filters/date_range.blade.php
  src/resources/views/crud/filters/range.blade.php
  src/resources/views/crud/filters/select2.blade.php
  src/resources/views/crud/filters/select2_ajax.blade.php
  src/resources/views/crud/filters/select2_multiple.blade.php
  src/resources/views/crud/filters/simple.blade.php
  src/resources/views/crud/filters/text.blade.php
Labels: Bug, refactoring

#2844 Add visual validation errors also to select fields
  src/resources/views/crud/form_content.blade.php
Labels: Bug

#2910 Fix pickers invalid feedback not displayed
  src/resources/views/crud/fields/date_picker.blade.php
  src/resources/views/crud/fields/datetime_picker.blade.php
Labels: Bug, non breaking change

#2919 Add french translation for base.php
  src/resources/lang/fr/base.php
Labels: needs-more-info

#2867 [4.1] Fix option order in select
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
Labels: Bug

#2834 Fixing undesired value on datetime inputs
  src/resources/views/crud/fields/datetime.blade.php
Labels: Bug

#2733 Serbian Translation
  src/resources/lang/sr/backup.php
  src/resources/lang/sr/base.php
  src/resources/lang/sr/crud.php
  src/resources/lang/sr/logmanager.php
  src/resources/lang/sr/pagemanager.php
  src/resources/lang/sr/permissionmanager.php
  src/resources/lang/sr/settings.php
Labels: Feature, Priority: SHOULD

#2937 Create translate routes only when needed
  src/app/Http/Controllers/Operations/UpdateOperation.php
Labels: Feature, Priority: SHOULD

#2947 Add missing Russian translation
  src/resources/lang/ru/crud.php
Labels: needs-more-info

#2954 [4.1] Fix widget viewNamespace
  src/resources/views/base/inc/widgets.blade.php
Labels: Bug

#2953 [4.X] Remove overflow hidden from crud table wrapper
  src/resources/views/crud/list.blade.php
Labels: Bug

#2960 [4.X] use json stringify instead of regex in table field
  src/resources/views/crud/fields/table.blade.php
Labels: Bug
