Repository Laravel-Backpack/CRUD, pull requests merged in 2020-10, with the labels that each got.

#3246 Remove init buttons
  src/app/Library/CrudPanel/CrudPanel.php
  tests/Unit/CrudPanel/CrudPanelTest.php
  tests/Unit/Http/Controllers/UserCrudController.php
  tests/Unit/Http/CrudControllerTest.php
  tests/config/database/migrations/2017_09_08_000001_create_addresses_table.php
Labels: Bug

#3258 bugfix options setting in tinymce field declaration
  src/resources/views/crud/fields/tinymce.blade.php
Labels: Minor Bug, Priority: SHOULD

#3266 fix chart widget not working when debugbar enabled
  src/app/Http/Controllers/ChartController.php
Labels: Minor Bug, Priority: SHOULD

#3270 Fix 2677
  src/resources/views/crud/reorder.blade.php
Labels: Minor Bug, Priority: COULD

#3269 Default user model is now the one in auth (fixes Class 'App\User' not found error when installing on Laravel 8)
  src/config/backpack/base.php
Labels: Bug, Priority: MUST, urgent

#3257 Do not register reset password routes if users do not have email
  src/config/backpack/base.php
  src/resources/views/base/auth/login.blade.php
  src/resources/views/base/auth/register.blade.php
  src/routes/backpack/base.php
Labels: Minor Bug

#3282 support new version of ocramius/package-versions
  composer.json
Labels: Priority: MUST

#3285 ran npm audit fix to bump resolve-url-loader version
  package-lock.json
  package.json
  src/public/packages/backpack/base/css/bundle.css
  src/public/packages/backpack/base/js/bundle.js
Labels: Priority: SHOULD

#3281 tinymce stores full image path instead of server relative path
  src/resources/views/crud/fields/tinymce.blade.php
Labels: Bug, Priority: MUST
