Repository Laravel-Backpack/CRUD, pull requests merged in 2020-11, with the labels that each got.

#3277 Added missing translatable icon to repeatable field
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Priority: SHOULD, needs-more-info

#3301 clear ajax select options when clearing the value
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
Labels: Minor Bug, non breaking change

#2253 [4.1.x][Bug fix] Update date range filter
  src/resources/lang/en/crud.php
  src/resources/lang/pt/crud.php
  src/resources/views/crud/fields/date_range.blade.php
  src/resources/views/crud/filters/date_range.blade.php
Labels: Bug

#3309 date field initializations should not rely on wrapper class
  src/resources/views/crud/fields/date_picker.blade.php
  src/resources/views/crud/fields/date_range.blade.php
  src/resources/views/crud/fields/datetime_picker.blade.php
Labels: Minor Bug, Priority: SHOULD

#3273 Do not reinitialize the instance again
  src/app/Models/Traits/HasRelationshipFields.php
Labels: Priority: MUST, Priority: SHOULD

#3274 [bug-fix] multiple click event registering in image field
  src/resources/views/crud/fields/base64_image.blade.php
  src/resources/views/crud/fields/image.blade.php
Labels: Priority: SHOULD

#3197 [MINOR] Add cachebusting to all backpack's assets
  src/resources/views/crud/form_content.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
  src/resources/views/crud/show.blade.php
Labels: Priority: SHOULD, non breaking change

#3307 Use Composer Suggestions - add main addons and tools as suggestions in composer.json
  composer.json
Labels: Feature, Priority: COULD, non breaking change

#3343 Resize DataTable on sidebar toggle
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Minor Bug, Priority: MUST

#3317 get un-casted value for casted attributes in radio
  src/resources/views/crud/fields/radio.blade.php
Labels: Priority: SHOULD
