Repository Laravel-Backpack/CRUD, pull requests merged in 2020-05, with the labels that each got.

#2737 EasyMDE field to replace SimpleMDE
  package-lock.json
  package.json
  src/public/packages/easymde/dist/easymde.min.css
  src/public/packages/easymde/dist/easymde.min.js
  src/resources/views/crud/fields/easymde.blade.php
  webpack.mix.js
Labels: Feature, refactoring

#2751 Fix select and order field inside repeatable
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/fields/select_and_order.blade.php
Labels: Bug

#2632 [4.1] [Fix] HasOne and BelongsTo relationship fixing
  src/app/Http/Controllers/Operations/UpdateOperation.php
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/fields/relationship.blade.php
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/select.blade.php
  src/resources/views/crud/fields/select2.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/CrudPanel/CrudPanelFieldsTest.php
  tests/Unit/Models/Address.php
Labels: Bug

#2769 [4.1-beta] Trying to fix name guessing
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: Bug

#2774 [4.1] Fix fetch closing empty option tag.
  src/resources/views/crud/fields/relationship/fetch.blade.php
Labels: needs-more-info

#2777 [4.1] Fix inline inside repeatable
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/inline_create_button.blade.php
Labels: Bug, needs-more-info

#2775 Fix angle icon on RTL Mode
  src/resources/views/crud/create.blade.php
Labels: needs-more-info

#2776 Fix Angle icon on RTL Mode, edit
  src/resources/views/crud/edit.blade.php
Labels: needs-more-info

#2732 [4.1-beta] fix fetch field with custom model accessor
  src/resources/views/crud/fields/relationship/fetch.blade.php
Labels: Bug, needs-more-info

#2748 [4.1.x] address_algolia field inside repeatable
  src/resources/views/crud/fields/address_algolia.blade.php
Labels: Bug, help wanted

#2596 [4.1.0][Feature][Merged] Chart widget + ChartController
  .travis.yml
  src/app/Http/Controllers/ChartController.php
  src/resources/views/base/widgets/chart.blade.php
Labels: Feature, Priority: MUST, Progress: Ready, non breaking change

#2479 [4.1][Feature][Ready] Setting to disable search inside list operation
  src/config/backpack/crud.php
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Feature, Priority: SHOULD, non breaking change

#2408 [4.1][Feature][Ready] Configurable web middleware
  src/config/backpack/base.php
  src/routes/backpack/base.php
  src/routes/backpack/custom.php
Labels: Priority: COULD, breaking change

#2363 [4.1][Bug] Missing font-awesome and update to latest one
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/css/all.min.css
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-brands-400.eot
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-brands-400.svg
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-brands-400.ttf
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-brands-400.woff
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-brands-400.woff2
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-regular-400.eot
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-regular-400.svg
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-regular-400.ttf
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-regular-400.woff
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-regular-400.woff2
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-solid-900.eot
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-solid-900.svg
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-solid-900.ttf
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-solid-900.woff
  src/public/packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.12.0-1/webfonts/fa-solid-900.woff2
  src/resources/views/crud/fields/icon_picker.blade.php
Labels: Bug, dependencies

#1963 [4.1][Improvement][Ready] Better revisions subheading
  src/resources/lang/en/crud.php
  src/resources/views/crud/revisions.blade.php
Labels: Priority: SHOULD

#2789 Relationship column was using an old method name
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/resources/views/crud/columns/relationship.blade.php
  src/resources/views/crud/fields/relationship/fetch.blade.php
Labels: Bug

#2805 fixes #2797 - CrudColumn constructor did not guess missing attributes
  src/app/Library/CrudPanel/CrudColumn.php
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
Labels: Bug

#2806 adds dump() and dd() methods to fluent syntax objects
  src/app/Library/CrudPanel/CrudButton.php
  src/app/Library/CrudPanel/CrudColumn.php
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/Widget.php
Labels: Feature

#2808 [BUGFIX] Fix icon picker triggering on enter
  src/resources/views/crud/fields/icon_picker.blade.php
Labels: Bug

#2818 [4.1] Fix FetchOperation with custom query
  src/app/Http/Controllers/Operations/FetchOperation.php
Labels: Bug

#2792 [4.1] Fixed include_all_form_fields option for relationship fields
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
Labels: Bug

#2830 [4.1.x] do not add route or sidebar content if it already exists
  src/app/Console/Commands/AddCustomRouteContent.php
  src/app/Console/Commands/AddSidebarContent.php
Labels: Feature

#2837 [4.1.x] Fix lonely dot in CRUD when no entries
  src/resources/lang/en/crud.php
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Bug

#2855 [4.1] Fixing enter key submit form on inline create
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/inline_create_modal.blade.php
Labels: Bug

#2854 [4.1][Bugfix] Fix wrong model checking isColumnNullable in select2
  src/resources/views/crud/fields/select2.blade.php
Labels: Bug

#2862 Add check before is_callable for wrapper attribute values
  src/resources/views/base/widgets/inc/wrapper_start.blade.php
  src/resources/views/crud/columns/inc/wrapper_start.blade.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
Labels: Bug, non breaking change

#2870 Added new widget stacks - before_breadcrumbs and after_breadcrumbs
  src/resources/views/base/blank.blade.php
  src/resources/views/base/layouts/top_left.blade.php
Labels: Feature
