Repository Laravel-Backpack/CRUD, pull requests merged in 2020-01, with the labels that each got.

#2369 [4.0][Bug fix] Add missing endphp tag like pr #2365
  src/resources/views/crud/fields/browse_multiple.blade.php
Labels: bug

#2352 Add Indonesian language at base.php
  src/resources/lang/id/base.php
Labels: needs-more-info

#2377 Sync 'zh-cn' lang files.
  src/resources/lang/zh-cn/base.php
  src/resources/lang/zh-cn/crud.php
Labels: needs-more-info

#2401 [4.0][BUG FIX] Fix dropdown filter active option state.
  src/resources/views/crud/filters/dropdown.blade.php
Labels: Bug, Priority: MUST, Progress: Ready
