Repository Laravel-Backpack/CRUD, pull requests merged in 2021-11, with the labels that each got.

#3606 Relationship columns definition
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/resources/views/crud/columns/select_multiple.blade.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
Labels: Bug, Priority: MUST

#3926 fix AutoSet never taking into account previously added columns
  src/app/Library/CrudPanel/Traits/AutoSet.php
Labels: Bug, Priority: MUST

#3927 ShowOperation should not add fields by default
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/app/Library/CrudPanel/Traits/AutoSet.php
Labels: Bug, non breaking change, Priority: SHOULD

#3929 Fix InlineCreate optional routes
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
Labels: Bug

#3903 Add custom defaults to columns
  src/resources/views/crud/columns/array.blade.php
  src/resources/views/crud/columns/array_count.blade.php
  src/resources/views/crud/columns/boolean.blade.php
  src/resources/views/crud/columns/check.blade.php
  src/resources/views/crud/columns/date.blade.php
  src/resources/views/crud/columns/datetime.blade.php
  src/resources/views/crud/columns/email.blade.php
  src/resources/views/crud/columns/image.blade.php
  src/resources/views/crud/columns/json.blade.php
  src/resources/views/crud/columns/markdown.blade.php
  src/resources/views/crud/columns/multidimensional_array.blade.php
  src/resources/views/crud/columns/number.blade.php
  src/resources/views/crud/columns/phone.blade.php
  src/resources/views/crud/columns/radio.blade.php
  src/resources/views/crud/columns/relationship_count.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_from_array.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
  src/resources/views/crud/columns/table.blade.php
  src/resources/views/crud/columns/text.blade.php
  src/resources/views/crud/columns/textarea.blade.php
  src/resources/views/crud/columns/upload_multiple.blade.php
  src/resources/views/crud/columns/video.blade.php
Labels: Feature, Priority: MUST

#3836 Catch jquery ajax errors
  src/resources/views/base/inc/scripts.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/inc/ajax_error_frame.blade.php
Labels: Feature, Priority: MUST

#3940 Add route facade to route file
  src/routes/backpack/base.php
  src/routes/backpack/custom.php
Labels: Priority: COULD

#3912 add script and style widgets
  src/resources/views/base/widgets/script.blade.php
  src/resources/views/base/widgets/style.blade.php
Labels: Feature, Priority: MUST

#3942 Remove broken functionality - default CSS and JS files for operations
  src/public/packages/backpack/base/img/spinner.svg
  src/public/packages/backpack/crud/css/create.css
  src/public/packages/backpack/crud/css/crud.css
  src/public/packages/backpack/crud/css/edit.css
  src/public/packages/backpack/crud/css/form.css
  src/public/packages/backpack/crud/css/list.css
  src/public/packages/backpack/crud/css/reorder.css
  src/public/packages/backpack/crud/css/revisions.css
  src/public/packages/backpack/crud/css/show.css
  src/public/packages/backpack/crud/img/ajax-loader.gif
  src/public/packages/backpack/crud/js/create.js
  src/public/packages/backpack/crud/js/crud.js
  src/public/packages/backpack/crud/js/edit.js
  src/public/packages/backpack/crud/js/form.js
  src/public/packages/backpack/crud/js/list.js
  src/public/packages/backpack/crud/js/reorder.js
  src/public/packages/backpack/crud/js/revisions.js
  src/public/packages/backpack/crud/js/show.js
  src/resources/views/crud/form_content.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
  src/resources/views/crud/show.blade.php
Labels: Priority: MUST

#3949 Added translations to date filter
  src/resources/views/crud/filters/date.blade.php
Labels: Bug

#3859 Default to escape true on all column types except `markdown` and `custom_html`
  src/resources/views/crud/columns/array.blade.php
  src/resources/views/crud/columns/array_count.blade.php
  src/resources/views/crud/columns/closure.blade.php
  src/resources/views/crud/columns/markdown.blade.php
  src/resources/views/crud/columns/model_function.blade.php
  src/resources/views/crud/columns/model_function_attribute.blade.php
  src/resources/views/crud/columns/relationship_count.blade.php
  src/resources/views/crud/columns/textarea.blade.php
Labels: Bug, Priority: MUST

#3905 [4.2] Refactor repeatable to use arrayed names
  src/app/Http/Controllers/Operations/FetchOperation.php
  src/resources/views/crud/fields/address_algolia.blade.php
  src/resources/views/crud/fields/address_google.blade.php
  src/resources/views/crud/fields/browse_multiple.blade.php
  src/resources/views/crud/fields/ckeditor.blade.php
  src/resources/views/crud/fields/date_range.blade.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
  src/resources/views/crud/fields/select2_multiple.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
Labels: breaking change, Priority: MUST

#3936 Add column `default` attribute & make that default consistent across column types
  src/resources/views/crud/columns/array.blade.php
  src/resources/views/crud/columns/array_count.blade.php
  src/resources/views/crud/columns/boolean.blade.php
  src/resources/views/crud/columns/check.blade.php
  src/resources/views/crud/columns/closure.blade.php
  src/resources/views/crud/columns/custom_html.blade.php
  src/resources/views/crud/columns/date.blade.php
  src/resources/views/crud/columns/datetime.blade.php
  src/resources/views/crud/columns/email.blade.php
  src/resources/views/crud/columns/image.blade.php
  src/resources/views/crud/columns/inc/details_row_button.blade.php
  src/resources/views/crud/columns/json.blade.php
  src/resources/views/crud/columns/markdown.blade.php
  src/resources/views/crud/columns/model_function.blade.php
  src/resources/views/crud/columns/model_function_attribute.blade.php
  src/resources/views/crud/columns/multidimensional_array.blade.php
  src/resources/views/crud/columns/number.blade.php
  src/resources/views/crud/columns/phone.blade.php
  src/resources/views/crud/columns/radio.blade.php
  src/resources/views/crud/columns/relationship.blade.php
  src/resources/views/crud/columns/relationship_count.blade.php
  src/resources/views/crud/columns/row_number.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_from_array.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
  src/resources/views/crud/columns/table.blade.php
  src/resources/views/crud/columns/text.blade.php
  src/resources/views/crud/columns/textarea.blade.php
  src/resources/views/crud/columns/upload_multiple.blade.php
  src/resources/views/crud/columns/video.blade.php
Labels: Feature, Priority: MUST

#3955 [4.2] Non-inputs start with underscore
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/app/Http/Controllers/Operations/UpdateOperation.php
  src/app/Library/CrudPanel/Traits/SaveActions.php
  src/app/Models/Traits/SpatieTranslatable/HasTranslations.php
  src/config/backpack/crud.php
  src/resources/views/crud/buttons/show.blade.php
  src/resources/views/crud/buttons/update.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/fields/relationship/form_content.blade.php
  src/resources/views/crud/form_content.blade.php
  src/resources/views/crud/inc/form_save_buttons.blade.php
  src/resources/views/crud/show.blade.php
Labels: breaking change, Priority: MUST

#3970 use @includeFirst() in show operation view
  src/resources/views/crud/show.blade.php
Labels: Priority: MUST
