Repository Laravel-Backpack/CRUD, pull requests merged in 2021-01, with the labels that each got.

#3332 ability to define paginator accordingly to documentation
  src/app/Library/CrudPanel/Traits/Read.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  tests/Unit/CrudPanel/CrudPanelReadTest.php
Labels: Minor Bug, Priority: SHOULD

#3358 Added functionality to allow for callables as wrapper elements
  src/resources/views/crud/columns/inc/wrapper_end.blade.php
  src/resources/views/crud/columns/inc/wrapper_start.blade.php
Labels: Feature, Priority: COULD

#3334 add consistent field null property
  src/resources/views/crud/fields/select.blade.php
  src/resources/views/crud/fields/select2.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_array.blade.php
  src/resources/views/crud/fields/select2_grouped.blade.php
  src/resources/views/crud/fields/select2_multiple.blade.php
  src/resources/views/crud/fields/select2_nested.blade.php
  src/resources/views/crud/fields/select_from_array.blade.php
  src/resources/views/crud/fields/select_grouped.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
Labels: Minor Bug, refactoring

#3428 Multiple order columns in Datatables
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: Minor Bug

#3445 [Bug] prevent relationship functionality when column has entity => false
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
Labels: Bug, Priority: MUST

#3469 remove asterisks from radio options
  src/public/packages/backpack/crud/css/form.css
Labels: Minor Bug

#3406 Allow repeatable fields to init custom rows and have a maximum of rows
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Priority: MUST

#3462 Translate some phrases (arabic)
  src/resources/lang/ar/base.php
Labels: needs-more-info

#3113 [4.1]Ease the get of inputs from dependant fields in api's
  src/helpers.php
Labels: Feature, Priority: SHOULD

#3475 testCrudRequestUpdatesOnEachRequest was failing in Laravel 7+
  tests/Unit/Http/CrudControllerTest.php
Labels: Priority: MUST

#3449 Fix image field for sftp driver
  src/resources/views/crud/fields/image.blade.php
Labels: Minor Bug

#3448 #3398 Fix for 'clause is ambiguous' when searching on joined tables, when tables have similar columns
  src/app/Library/CrudPanel/Traits/Search.php
Labels: Bug, Priority: MUST
