Repository Laravel-Backpack/CRUD, pull requests merged in 2021-03, with the labels that each got.

#3563 add json as text column type
  src/app/Http/Controllers/Operations/FetchOperation.php
Labels: Bug

#3527 Unique emails on tests
  tests/config/database/seeds/UsersTableSeeder.php
Labels: Bug

#3566 fix datatables reseting page length
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Bug

#3553 Fix for vimeo API
  src/resources/views/crud/fields/video.blade.php
Labels: Bug

#3570 [Bug] Array fields don't show the required red asterisk
  src/app/Library/CrudPanel/Traits/Validation.php
Labels: Minor Bug, Priority: SHOULD

#3573 [Bug] Radio field on a boolean attribute interprets old value incorrectly
  src/resources/views/crud/fields/radio.blade.php
Labels: Bug

#3572 [Bug] SluggableObserver declaration fix
  src/app/Models/Traits/SpatieTranslatable/SluggableObserver.php
Labels: Bug

#3532 [Bug] DataTables resetting to first page on bulk actions
  src/resources/views/crud/buttons/bulk_clone.blade.php
  src/resources/views/crud/buttons/bulk_delete.blade.php
  src/resources/views/crud/buttons/clone.blade.php
  src/resources/views/crud/buttons/delete.blade.php
Labels: Bug

#3596 Only apply table prefix when query contains joins
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Minor Bug

#3582 remove select2_ajax filter artifacts left behind in url
  src/resources/views/crud/filters/select2.blade.php
  src/resources/views/crud/filters/select2_ajax.blade.php
  src/resources/views/crud/filters/select2_multiple.blade.php
  src/resources/views/crud/inc/filters_navbar.blade.php
Labels: Minor Bug, Priority: SHOULD

#3558 Fix eager load nested relationships
  src/app/Library/CrudPanel/Traits/Read.php
Labels: Bug

#3607 refactor for L6 compatibility
  src/app/Library/CrudPanel/Traits/Validation.php
Labels: Bug

#3538 prefixes in repeatable fields that need them
  src/resources/views/crud/fields/image.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Minor Bug

#3623 Fix russian localization
  src/resources/lang/ru/base.php
  src/resources/lang/ru/crud.php
Labels: needs-more-info

#3614 Fix a couple of docblocks for better IDE support
  src/app/Http/Controllers/Operations/CreateOperation.php
  src/app/Http/Controllers/Operations/UpdateOperation.php
Labels: needs-more-info

#3634 Fix search when devs use prefixed database tables
  src/app/Library/CrudPanel/Traits/Search.php
Labels: Bug, Priority: MUST

#3595 [Bug] Unable to modify the wrapper classes of upload field
  src/resources/views/crud/fields/address_algolia.blade.php
  src/resources/views/crud/fields/browse_multiple.blade.php
  src/resources/views/crud/fields/hidden.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
Labels: Bug
