Repository Laravel-Backpack/CRUD, pull requests merged in 2021-05, with the labels that each got.

#3698 translated the rest of the entries that wasn't translated in Arabic
  src/resources/lang/ar/base.php
  src/resources/lang/ar/crud.php
Labels: needs-more-info

#3643 Dont call identifiable attribute in models that dont use crud trait
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: Minor Bug

#3541 dont add the orders to table instead of clearing them
  src/app/Http/Controllers/Operations/ListOperation.php
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Bug

#3708 Typo fix
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: needs-more-info

#3705 do not check for nullness
  src/app/Library/CrudPanel/Traits/Create.php
Labels: Bug

#3687 AccountInfoRequest validation connection support
  src/app/Http/Requests/AccountInfoRequest.php
Labels: Minor Bug

#3724 Added Bangla Translation
  src/resources/lang/bn/backup.php
  src/resources/lang/bn/base.php
  src/resources/lang/bn/crud.php
  src/resources/lang/bn/logmanager.php
  src/resources/lang/bn/pagemanager.php
  src/resources/lang/bn/permissionmanager.php
  src/resources/lang/bn/settings.php
Labels: needs-more-info

#3625 Remove redundant makeSlugUnique method overriding
  src/app/Models/Traits/SpatieTranslatable/SlugService.php
Labels: Bug

#3719 Added missing LangFileManager translation links
  src/resources/lang/ar/langfilemanager.php
  src/resources/lang/bg/langfilemanager.php
  src/resources/lang/cs/langfilemanager.php
  src/resources/lang/da-DK/langfilemanager.php
  src/resources/lang/da_DK/langfilemanager.php
  src/resources/lang/de/langfilemanager.php
  src/resources/lang/el/langfilemanager.php
  src/resources/lang/en/langfilemanager.php
  src/resources/lang/es/langfilemanager.php
  src/resources/lang/fa/langfilemanager.php
  src/resources/lang/fr-CA/langfilemanager.php
  src/resources/lang/fr/langfilemanager.php
  src/resources/lang/fr_CA/langfilemanager.php
  src/resources/lang/gr/langfilemanager.php
  src/resources/lang/hu/langfilemanager.php
  src/resources/lang/id/langfilemanager.php
  src/resources/lang/it/langfilemanager.php
  src/resources/lang/ja/langfilemanager.php
  src/resources/lang/lo/langfilemanager.php
  src/resources/lang/lv/langfilemanager.php
  src/resources/lang/nl/langfilemanager.php
  src/resources/lang/pt-BR/langfilemanager.php
  src/resources/lang/pt/langfilemanager.php
  src/resources/lang/pt_br/langfilemanager.php
  src/resources/lang/ro/langfilemanager.php
  src/resources/lang/ru/langfilemanager.php
  src/resources/lang/sr/langfilemanager.php
  src/resources/lang/tr/langfilemanager.php
  src/resources/lang/uk/langfilemanager.php
  src/resources/lang/zh-Hant/langfilemanager.php
  src/resources/lang/zh-cn/langfilemanager.php
Labels: Minor Bug
