Repository Laravel-Backpack/CRUD, pull requests merged in 2021-02, with the labels that each got.

#3347 Allow doctrine/dbal ^3.0 as laravel 8.15 supports it
  composer.json
Labels: Feature, Priority: MUST

#3451 Fixed hasOrderByPrimaryKey evaluation
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: Minor Bug

#3511 [BUG] upload_multiple does not allow to delete and store files in the same request
  src/resources/views/crud/fields/upload_multiple.blade.php
Labels: Bug

#3516 Add PHP8 support
  .github/workflows/testing.yml
  composer.json
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
Labels: Priority: MUST

#3484 Disabled the animation during page load
  src/resources/views/base/inc/sidebar.blade.php
Labels: Minor Bug

#3509 The endDate format miss an H in format, when the hidden fields value are set in the javascript
  src/resources/views/crud/fields/date_range.blade.php
Labels: Bug

#3397 Fix for select2 to match other inputs height
  src/public/packages/backpack/crud/css/form.css
Labels: Minor Bug

#3447 Added Backpack fallback route
  src/routes/backpack/base.php
Labels: Bug

#3512 use filter key instead of name in range filter
  src/resources/views/crud/filters/range.blade.php
Labels: Bug

#3313 field dependant functionality fixes
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
Labels: Bug, Priority: MUST

#3477 Moved pac-container up in z to be visible
  src/resources/views/crud/fields/address_google.blade.php
Labels: Bug

#3517 Added DBAL v3 support
  .github/workflows/testing.yml
  composer.json
  src/app/Library/CrudPanel/Traits/AutoSet.php
  src/app/Models/Traits/HasRelationshipFields.php
  tests/Unit/CrudPanel/CrudPanelAutoSetTest.php
Labels: Priority: MUST

#3079 [4.X] Fixing alerts when redirected by persistent table
  src/resources/views/base/inc/alerts.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Bug, Priority: MUST

#3526 refactor #3267 before merging
  src/resources/lang/en/crud.php
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
Labels: Minor Bug

#3435 Added prefix and suffix to columns
  src/resources/views/crud/columns/array.blade.php
  src/resources/views/crud/columns/array_count.blade.php
  src/resources/views/crud/columns/boolean.blade.php
  src/resources/views/crud/columns/check.blade.php
  src/resources/views/crud/columns/closure.blade.php
  src/resources/views/crud/columns/custom_html.blade.php
  src/resources/views/crud/columns/date.blade.php
  src/resources/views/crud/columns/datetime.blade.php
  src/resources/views/crud/columns/email.blade.php
  src/resources/views/crud/columns/json.blade.php
  src/resources/views/crud/columns/markdown.blade.php
  src/resources/views/crud/columns/multidimensional_array.blade.php
  src/resources/views/crud/columns/number.blade.php
  src/resources/views/crud/columns/phone.blade.php
  src/resources/views/crud/columns/radio.blade.php
  src/resources/views/crud/columns/relationship_count.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_from_array.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
  src/resources/views/crud/columns/textarea.blade.php
Labels: Feature

#3522 infer ajax from data_source if no ajax specified
  src/resources/views/crud/fields/relationship.blade.php
Labels: Minor Bug

#3504 Fix issue where a nested relation on column would cause an exception on listing
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/resources/views/crud/columns/relationship.blade.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
  tests/Unit/Models/AccountDetails.php
  tests/config/database/migrations/2017_09_08_000001_create_account_details_table.php
Labels: Bug

#3550 fix sql vector in order by clauses
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: Bug, urgent

#3547 Configurable delay on ajax fields
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/filters/select2_ajax.blade.php
Labels: Minor Bug

#3551 use onreadystatechange in favor of DOMContentLoad
  src/resources/views/base/inc/alerts.blade.php
Labels: Bug
