Repository Laravel-Backpack/CRUD, pull requests merged in 2021-04, with the labels that each got.

#3637 Fix ru localization
  src/resources/lang/ru/base.php
  src/resources/lang/ru/crud.php
Labels: needs-more-info

#3664 Added Ukrainian translation.
  src/resources/lang/uk/backup.php
  src/resources/lang/uk/base.php
  src/resources/lang/uk/crud.php
  src/resources/lang/uk/logmanager.php
  src/resources/lang/uk/pagemanager.php
  src/resources/lang/uk/permissionmanager.php
  src/resources/lang/uk/settings.php
Labels: needs-more-info

#3640 Replace null coalescing operator with ternary, fixes #3639
  src/resources/views/base/inc/alerts.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: refactoring

#3657 getColumnType does not need table prefix
  src/app/Models/Traits/HasRelationshipFields.php
  tests/Unit/CrudPanel/BasePrefixedDBCrudPanelTest.php
  tests/Unit/CrudPanel/CrudPanelTablePrefixedTests.php
Labels: Bug, Priority: MUST

#3648 Corrected by passing parameter by reference
  src/resources/views/crud/columns/select.blade.php
Labels: Bug

#3663 fix update with id=0
  src/app/Library/CrudPanel/Traits/Read.php
Labels: Minor Bug, Priority: COULD

#3669 remove double closing tags in inline create button
  src/resources/views/crud/fields/relationship/inline_create_button.blade.php
Labels: Minor Bug

#3670 fix echoing of select2 nested
  src/resources/views/crud/fields/select2_nested.blade.php
Labels: Bug

#3598 select2 add i18n for other locale
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/select2.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
  src/resources/views/crud/fields/select2_from_array.blade.php
  src/resources/views/crud/fields/select2_grouped.blade.php
  src/resources/views/crud/fields/select2_multiple.blade.php
  src/resources/views/crud/fields/select2_nested.blade.php
  src/resources/views/crud/filters/select2.blade.php
  src/resources/views/crud/filters/select2_ajax.blade.php
  src/resources/views/crud/filters/select2_multiple.blade.php
Labels: Bug
