Repository Laravel-Backpack/CRUD, pull requests merged in 2021-09, with the labels that each got.

#3671 Add back IE support (fix conflicting code)
  src/resources/views/base/inc/alerts.blade.php
  src/resources/views/base/inc/scripts.blade.php
  src/resources/views/base/inc/sidebar.blade.php
  src/resources/views/crud/fields/image.blade.php
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
  src/resources/views/crud/fields/video.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/inc/export_buttons.blade.php
Labels: Bug, Priority: SHOULD

#3779 fix required repeatable fields
  src/public/packages/backpack/crud/css/form.css
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/form_content.blade.php
Labels: Minor Bug

#3822 change placeholder URL
  src/helpers.php
Labels: Priority: SHOULD

#3530 Fire 'change' event when selecting radio elements
  src/resources/views/crud/fields/radio.blade.php
Labels: non breaking change

#3816 fix for 0 key in select from array
  src/resources/views/crud/fields/select_from_array.blade.php
Labels: Bug, Priority: SHOULD

#3624 visibleInShow closure
  src/app/Http/Controllers/Operations/ShowOperation.php
Labels: Feature Request

#3813 Require devtools command
  src/BackpackServiceProvider.php
  src/app/Console/Commands/Install.php
  src/app/Console/Commands/RequireDevTools.php
  src/app/Console/Commands/Traits/PrettyCommandOutput.php
Labels: URGENT, Feature, Priority: MUST

#3826 If possible relation method requires parameters, it's not a relation method.
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
Labels: Bug

#3837 Prevent DB query when value is empty
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
Labels: Bug, URGENT

#3654 Fix repeatable converting non-string values to string when adding prefix
  src/resources/views/crud/fields/repeatable.blade.php
Labels: non breaking change, Minor Bug
