Repository Laravel-Backpack/CRUD, pull requests merged in 2021-12, with the labels that each got.

#3616 Add option to warn user before leaving create or edit page
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/WarnBeforeLeaving.php
  src/config/backpack/crud.php
  src/resources/views/crud/form_content.blade.php
Labels: Feature Request

#3986 Move operation configs to separate files
  src/BackpackServiceProvider.php
  src/app/Library/CrudPanel/Traits/Settings.php
  src/config/backpack/crud.php
  src/config/backpack/operations/create.php
  src/config/backpack/operations/list.php
  src/config/backpack/operations/reorder.php
  src/config/backpack/operations/show.php
  src/config/backpack/operations/update.php
Labels: breaking change, Priority: MUST, refactoring

#3459 Refactor page or link field
  src/resources/views/crud/fields/page_or_link.blade.php
Labels: Bug, breaking change, Priority: MUST, Priority: SHOULD, refactoring

#3993 changed column three dots to ellipsis
  src/resources/views/crud/columns/email.blade.php
  src/resources/views/crud/columns/model_function.blade.php
  src/resources/views/crud/columns/model_function_attribute.blade.php
  src/resources/views/crud/columns/phone.blade.php
  src/resources/views/crud/columns/row_number.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
  src/resources/views/crud/columns/text.blade.php
Labels: Priority: COULD

#3996 Save fields without overwrites, and overwrite when needed
  .github/release-drafter.yml
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/Traits/AutoSet.php
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/FieldsPrivateMethods.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
  tests/Unit/CrudPanel/CrudPanelFieldsTest.php
Labels: URGENT, non breaking change, Priority: MUST

#3618 Detect suitable column type based on model casts
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
Labels: non breaking change, Priority: MUST, Priority: SHOULD

#2652 [4.2.x] Fix CSS / JS assets loaded multiple times
  composer.json
  src/app/Http/Controllers/Operations/InlineCreateOperation.php
  src/resources/views/base/widgets/chart.blade.php
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/fields/address_algolia.blade.php
  src/resources/views/crud/fields/address_google.blade.php
  src/resources/views/crud/fields/base64_image.blade.php
  src/resources/views/crud/fields/browse.blade.php
  src/resources/views/crud/fields/browse_multiple.blade.php
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/checklist.blade.php
  src/resources/views/crud/fields/checklist_dependency.blade.php
  src/resources/views/crud/fields/ckeditor.blade.php
  src/resources/views/crud/fields/color_picker.blade.php
  src/resources/views/crud/fields/date_picker.blade.php
  src/resources/views/crud/fields/date_range.blade.php
  src/resources/views/crud/fields/datetime_picker.blade.php
  src/resources/views/crud/fields/easymde.blade.php
  src/resources/views/crud/fields/icon_picker.blade.php
  src/resources/views/crud/fields/image.blade.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/relationship/field_attributes.blade.php
  src/resources/views/crud/fields/relationship/inline_create_modal.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/fields/select2.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
  src/resources/views/crud/fields/select2_from_array.blade.php
  src/resources/views/crud/fields/select2_grouped.blade.php
  src/resources/views/crud/fields/select2_multiple.blade.php
  src/resources/views/crud/fields/select2_nested.blade.php
  src/resources/views/crud/fields/select_and_order.blade.php
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/fields/table.blade.php
  src/resources/views/crud/fields/tinymce.blade.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
  src/resources/views/crud/fields/video.blade.php
Labels: Priority: MUST, Priority: SHOULD

#4005 Replaced `is_callable` with `instanceof \Closure`
  src/resources/views/crud/columns/array.blade.php
  src/resources/views/crud/columns/array_count.blade.php
  src/resources/views/crud/columns/boolean.blade.php
  src/resources/views/crud/columns/check.blade.php
  src/resources/views/crud/columns/closure.blade.php
  src/resources/views/crud/columns/custom_html.blade.php
  src/resources/views/crud/columns/date.blade.php
  src/resources/views/crud/columns/datetime.blade.php
  src/resources/views/crud/columns/email.blade.php
  src/resources/views/crud/columns/image.blade.php
  src/resources/views/crud/columns/inc/wrapper_end.blade.php
  src/resources/views/crud/columns/inc/wrapper_start.blade.php
  src/resources/views/crud/columns/json.blade.php
  src/resources/views/crud/columns/markdown.blade.php
  src/resources/views/crud/columns/model_function.blade.php
  src/resources/views/crud/columns/model_function_attribute.blade.php
  src/resources/views/crud/columns/multidimensional_array.blade.php
  src/resources/views/crud/columns/number.blade.php
  src/resources/views/crud/columns/phone.blade.php
  src/resources/views/crud/columns/radio.blade.php
  src/resources/views/crud/columns/relationship_count.blade.php
  src/resources/views/crud/columns/row_number.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_from_array.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
  src/resources/views/crud/columns/table.blade.php
  src/resources/views/crud/columns/text.blade.php
  src/resources/views/crud/columns/textarea.blade.php
  src/resources/views/crud/columns/upload_multiple.blade.php
  src/resources/views/crud/columns/video.blade.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
Labels: Bug, Priority: MUST

#4006 Show operation add timestamps by default
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/config/backpack/operations/show.php
Labels: breaking change, Feature, Priority: SHOULD

#4007 Show operation add softdeletes support
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/config/backpack/operations/show.php
Labels: breaking change, Feature, Priority: SHOULD

#3132 [4.2] Move Show operation setup in its own method
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/config/backpack/operations/show.php
Labels: Bug, breaking change, Priority: MUST

#4002 Granular relationships refactor - Step 3 - pivot relations
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/fields/relationship.blade.php
  src/resources/views/crud/fields/relationship/repeatable_relation.blade.php
  tests/Unit/CrudPanel/BaseDBCrudPanelTest.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/Models/Bill.php
  tests/Unit/Models/Comment.php
  tests/Unit/Models/Recommend.php
  tests/Unit/Models/Star.php
  tests/Unit/Models/User.php
  tests/config/database/migrations/2020_03_31_114745_create_pivotable_relations_tables.php
  tests/config/database/seeds/MorphableSeeders.php
Labels: breaking change, Priority: MUST

#4011 Add parameter check for relationship guessing in fields
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: Priority: MUST

#4013 [Relationships] Hasone and morphone
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
Labels: Priority: MUST

#4014 Add number_columns option to checklist field
  src/resources/views/crud/fields/checklist.blade.php
Labels: Priority: SHOULD

#4020 Don't re-associate belongs to relations
  src/app/Library/CrudPanel/Traits/Create.php
Labels: Priority: MUST

#4022 Add PHP 8.1 support
  .github/workflows/testing.yml
Labels: Priority: MUST

#3995 Fix underscore in field name when using fetch operation
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
Labels: Bug, non breaking change, Priority: MUST

#4025 add hidden field for relationship select
  src/app/Library/CrudPanel/Traits/Create.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
Labels: Priority: MUST

#4016 [Relationships] Hasmany morphmany
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/app/Models/Traits/HasRelationshipFields.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/relationship.blade.php
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/relationship/repeatable_relation.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/Models/Comet.php
  tests/Unit/Models/Planet.php
  tests/Unit/Models/Universe.php
  tests/Unit/Models/User.php
  tests/config/database/migrations/2020_03_31_114745_create_pivotable_relations_tables.php
  tests/config/database/seeds/MorphableSeeders.php
Labels: Priority: MUST

#4004 Validation inside CrudController, from array or field definition
  src/app/Library/CrudPanel/Traits/Validation.php
Labels: Feature, non breaking change, Priority: MUST

#4009 Add support for Eloquent Model events to fields
  src/app/Http/Controllers/Operations/CreateOperation.php
  src/app/Http/Controllers/Operations/UpdateOperation.php
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Fields.php
Labels: Feature, non breaking change, Priority: MUST

#4018 Fix select_and_order does not respond to touch events
  mix-manifest.json
  package-lock.json
  package.json
  src/public/packages/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js
  src/resources/views/crud/fields/select_and_order.blade.php
  webpack.mix.js
Labels: Bug, Priority: MUST

#4028 Sync relations fix
  src/app/Library/CrudPanel/Traits/Create.php
Labels: Bug, Priority: MUST

#4041 Fix column guessing when translations enabled
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
Labels: Bug

#4043 Add some defaults for easier field setup
  src/resources/views/crud/fields/checklist.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
Labels: non breaking change, Priority: SHOULD

#3054 Create old input wrapper to solve old() sessions problems.
  src/helpers.php
  src/resources/views/crud/fields/address_algolia.blade.php
  src/resources/views/crud/fields/address_google.blade.php
  src/resources/views/crud/fields/base64_image.blade.php
  src/resources/views/crud/fields/browse.blade.php
  src/resources/views/crud/fields/browse_multiple.blade.php
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/checklist.blade.php
  src/resources/views/crud/fields/checklist_dependency.blade.php
  src/resources/views/crud/fields/ckeditor.blade.php
  src/resources/views/crud/fields/color.blade.php
  src/resources/views/crud/fields/color_picker.blade.php
  src/resources/views/crud/fields/date.blade.php
  src/resources/views/crud/fields/date_picker.blade.php
  src/resources/views/crud/fields/date_range.blade.php
  src/resources/views/crud/fields/datetime.blade.php
  src/resources/views/crud/fields/datetime_picker.blade.php
  src/resources/views/crud/fields/easymde.blade.php
  src/resources/views/crud/fields/email.blade.php
  src/resources/views/crud/fields/enum.blade.php
  src/resources/views/crud/fields/hidden.blade.php
  src/resources/views/crud/fields/icon_picker.blade.php
  src/resources/views/crud/fields/image.blade.php
  src/resources/views/crud/fields/month.blade.php
  src/resources/views/crud/fields/number.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/range.blade.php
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/fields/select.blade.php
  src/resources/views/crud/fields/select2.blade.php
  src/resources/views/crud/fields/select2_from_ajax.blade.php
  src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php
  src/resources/views/crud/fields/select2_from_array.blade.php
  src/resources/views/crud/fields/select2_grouped.blade.php
  src/resources/views/crud/fields/select2_multiple.blade.php
  src/resources/views/crud/fields/select2_nested.blade.php
  src/resources/views/crud/fields/select_and_order.blade.php
  src/resources/views/crud/fields/select_from_array.blade.php
  src/resources/views/crud/fields/select_grouped.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/fields/table.blade.php
  src/resources/views/crud/fields/text.blade.php
  src/resources/views/crud/fields/textarea.blade.php
  src/resources/views/crud/fields/time.blade.php
  src/resources/views/crud/fields/tinymce.blade.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
  src/resources/views/crud/fields/url.blade.php
  src/resources/views/crud/fields/video.blade.php
  src/resources/views/crud/fields/week.blade.php
Labels: Bug, non breaking change, Priority: MUST
