Repository Laravel-Backpack/CRUD, pull requests merged in 2022-01, with the labels that each got.

#3331 Fix the design of the crud table when bulk actions are enable
  mix-manifest.json
  src/app/Library/CrudPanel/Traits/Read.php
  src/app/Library/CrudPanel/Traits/Search.php
  src/public/packages/@digitallyhappy/backstrap/css/blue.css
  src/public/packages/@digitallyhappy/backstrap/css/blue.css.map
  src/public/packages/@digitallyhappy/backstrap/css/blue.min.css
  src/public/packages/@digitallyhappy/backstrap/css/blue.min.css.map
  src/public/packages/@digitallyhappy/backstrap/css/style.css
  src/public/packages/@digitallyhappy/backstrap/css/style.css.map
  src/public/packages/@digitallyhappy/backstrap/css/style.min.css
  src/public/packages/@digitallyhappy/backstrap/css/style.min.css.map
  src/public/packages/backpack/base/css/blue-bundle.css
  src/public/packages/backpack/base/css/bundle.css
  src/resources/assets/scss/blue-bundle.scss
  src/resources/assets/scss/bundle.scss
  src/resources/assets/scss/customs/_crud.scss
  src/resources/assets/scss/customs/_form.scss
  src/resources/assets/scss/customs/_list.scss
  src/resources/views/crud/columns/checkbox.blade.php
  src/resources/views/crud/columns/inc/bulk_actions_checkbox.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/list.blade.php
Labels: URGENT, breaking change, Priority: MUST

#4052 Fix old checklistdependency
  src/resources/views/crud/fields/checklist_dependency.blade.php
Labels: Bug

#4032 Change repeatable names on display
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Bug, Priority: MUST

#4054 [4.2] Make relationship field treat ALL relationship types
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/resources/views/crud/fields/relationship.blade.php
Labels: Priority: MUST

#4055 Fix select2_nested in 4.2 - account for a model being returned
  src/resources/views/crud/fields/select2_nested.blade.php
Labels: Bug, Priority: MUST

#4063 Fix repeatable name re-indexing on multiple inputs
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Bug

#4057 Fix checklist with reselection from old values
  src/resources/views/crud/fields/checklist_dependency.blade.php
Labels: Bug, Priority: MUST

#4064 [Pivot Relations] Pivot Selector should not allow to re-select the same.
  src/resources/views/crud/fields/relationship/fetch.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/relationship_select.blade.php
  src/resources/views/crud/fields/relationship/repeatable_relation.blade.php
Labels: Bug

#4070 [4.2] make default min_rows in repeatable zero
  src/resources/views/crud/fields/repeatable.blade.php
Labels: breaking change, Priority: MUST, Minor Bug

#4072 Fix checklist dependency when field is cleared
  src/resources/views/crud/fields/checklist_dependency.blade.php
Labels: Bug

#4066 Add `relationship.entry` subfield for single HasOne/MorphOne
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/fields/relationship.blade.php
  src/resources/views/crud/fields/relationship/entry.blade.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
Labels: Priority: MUST

#4062 [4.2] Clean up relationship directory - move partials to `inc` subdirectory & rename `relationship_select` and `repeatable_relation`
  src/app/Http/Controllers/Operations/InlineCreateOperation.php
  src/resources/views/crud/fields/relationship.blade.php
  src/resources/views/crud/fields/relationship/entries.blade.php
  src/resources/views/crud/fields/relationship/fetch_or_create.blade.php
  src/resources/views/crud/fields/relationship/field_attributes.blade.php
  src/resources/views/crud/fields/relationship/inc/form_content.blade.php
  src/resources/views/crud/fields/relationship/inc/inline_create_button.blade.php
  src/resources/views/crud/fields/relationship/inc/inline_create_modal.blade.php
  src/resources/views/crud/fields/relationship/inc/show_fields.blade.php
  src/resources/views/crud/fields/relationship/inc/show_tabbed_fields.blade.php
  src/resources/views/crud/fields/relationship/select.blade.php
Labels: Priority: MUST

#4077 Subfields in repeatable should not be treated as relationships
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
Labels: Bug

#4075 Fix corner case in hasOne and morphOne saving
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
Labels: Bug, Priority: MUST

#4081 Fix pivot field in repeatable
  src/resources/views/crud/fields/relationship/entries.blade.php
Labels: Bug

#4082 Make repeatable subfields `text` by default
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/relationship/entries.blade.php
Labels: Bug, breaking change, Priority: MUST

#4069 Allow other fields to use `subfields` attribute (not just `checklist_dependency`)
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/fields/date_range.blade.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/relationship.blade.php
  src/resources/views/crud/fields/relationship/entries.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Priority: MUST

#4068 Fix to allow enter key to select an option from address_google list of options without submitting the form.
  src/resources/views/crud/fields/address_google.blade.php
Labels: Minor Bug

#4083 Refactor last pivotFields instance, refactor tests
  src/app/Library/CrudPanel/Traits/Create.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
Labels: Bug

#4086 Get all pivot attributes in one go
  src/app/Library/CrudPanel/Traits/Update.php
Labels: Priority: MUST

#4084 Add orderColumn to repeatable to work with pivot orders
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/relationship/entries.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
Labels: Bug

#4094 Add support for Laravel 9
  README.md
  composer.json
  src/BackpackServiceProvider.php
Labels: Priority: MUST

#3967 [4.2] multiple namespace fallbacks for fields, columns, filters, buttons, widgets
  src/app/Library/CrudPanel/CrudButton.php
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/Traits/Search.php
  src/app/Library/Widget.php
  src/config/backpack/base.php
  src/config/backpack/crud.php
  src/resources/views/base/inc/widgets.blade.php
  src/resources/views/crud/inc/filters_navbar.blade.php
  src/resources/views/crud/inc/show_fields.blade.php
  src/resources/views/crud/show.blade.php
Labels: Priority: MUST

#4102 Use Str::markdown() instead of Mail
  composer.json
  src/resources/views/crud/columns/markdown.blade.php
Labels: Priority: MUST

#4067 Update address_google field with the ability to specify a return language so that the information stored as JSON is in the same language regardless of user locale
  src/resources/views/crud/fields/address_google.blade.php
Labels: Bug, Priority: MUST, Priority: SHOULD, affected-by-open-core-split

#4105 fix 4.1 select2_from_array using 0 as key.
  src/resources/views/crud/fields/select2_from_array.blade.php
Labels: Bug

#4095 Refactor relationship creation
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/helpers.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/Models/AccountDetails.php
  tests/Unit/Models/Bang.php
  tests/config/database/migrations/2020_03_31_114745_create_pivotable_relations_tables.php
  tests/config/database/seeds/MorphableSeeders.php
Labels: Priority: MUST

#4112 [4.2] guess attributes for subfields too (not just fields)
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/relationship/entries.blade.php
Labels: Priority: MUST

#4114 [4.2] fix select_multiple field on editing
  src/resources/views/crud/fields/select_multiple.blade.php
Labels: Priority: MUST

#4087 Moving first column buttons back to the first column
  src/app/Library/CrudPanel/Traits/Search.php
  src/resources/assets/scss/customs/_list.scss
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/list.blade.php
Labels: URGENT, Priority: MUST

#4119 change default column limit to 32
  src/resources/views/crud/columns/email.blade.php
  src/resources/views/crud/columns/model_function.blade.php
  src/resources/views/crud/columns/model_function_attribute.blade.php
  src/resources/views/crud/columns/phone.blade.php
  src/resources/views/crud/columns/row_number.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
  src/resources/views/crud/columns/text.blade.php
Labels: Priority: MUST, Minor Bug

#4116 Initialize subfields when defined
  src/app/Library/CrudPanel/Traits/Fields.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
Labels: Priority: MUST

#4122 Move subfield attribute guessing and add `CrudField::subfields()`
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/resources/views/crud/fields/inc/repeatable_row.blade.php
  src/resources/views/crud/fields/relationship/entries.blade.php
Labels: Priority: MUST
