Repository Laravel-Backpack/CRUD, pull requests merged in 2022-12, with the labels that each got.

#4811 fix how to contribute tutorial link
  CONTRIBUTING.md
Labels: Priority: MUST

#4796 [Bug] Missing query bindings lead to error when using `withCount` in the query.
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Bug, Priority: MUST

#4810 account for the possibility that save actions are not defined
  src/app/Library/CrudPanel/Traits/SaveActions.php
Labels: Priority: MUST

#4778 Add tests
  phpunit.xml
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/helpers.php
  tests/BaseTest.php
  tests/Unit/CrudPanel/CrudPanelAutoSetTest.php
  tests/Unit/CrudPanel/CrudPanelAutofocusTest.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/CrudPanel/CrudPanelDeleteTest.php
  tests/Unit/CrudPanel/CrudPanelErrorsTest.php
  tests/Unit/CrudPanel/CrudPanelFieldsTest.php
  tests/Unit/CrudPanel/CrudPanelFiltersTest.php
  tests/Unit/CrudPanel/CrudPanelMacroTest.php
  tests/Unit/CrudPanel/CrudPanelOperationsTest.php
  tests/Unit/CrudPanel/CrudPanelTitlesAndHeadingsTest.php
  tests/Unit/CrudPanel/CrudPanelUpdateTest.php
  tests/Unit/CrudPanel/ViewNamespacesTest.php
  tests/Unit/Models/User.php
  tests81/Unit/CrudPanel/CrudPanelFieldsTest.php
  tests81/Unit/Models/UserWithReturnTypes.php
Labels: Priority: MUST

#4821 Add more tests, attempt to fix coverage color
  .github/workflows/coverage.yml
  src/app/Library/CrudPanel/CrudButton.php
  src/app/Library/CrudPanel/CrudColumn.php
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/CrudPanelFacade.php
  tests/Unit/CrudPanel/CrudPanelButtonsTest.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
  tests/Unit/CrudPanel/CrudPanelFieldsTest.php
  tests/Unit/CrudPanel/CrudPanelFiltersTest.php
Labels: Priority: MUST

#4823 use request set in crud instead of global request instance
  src/app/Library/CrudPanel/CrudFilter.php
  tests/Unit/CrudPanel/CrudPanelFiltersTest.php
Labels: Priority: MUST, Minor Bug

#4824 more tests
  phpunit.xml
  src/BackpackServiceProvider.php
  src/app/Http/Controllers/CrudController.php
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/HasViewNamespaces.php
  src/app/Library/CrudPanel/Traits/SaveActions.php
  src/routes/backpack/testing.php
  tests/Unit/CrudPanel/CrudPanelAutoSetTest.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
  tests/Unit/CrudPanel/CrudPanelFiltersTest.php
  tests/Unit/CrudPanel/CrudPanelReadTest.php
  tests/Unit/CrudPanel/CrudPanelSaveActionsTest.php
  tests/Unit/CrudPanel/CrudPanelTest.php
  tests/Unit/CrudPanel/CrudPanelTitlesAndHeadingsTest.php
  tests/Unit/CrudPanel/ViewNamespacesTest.php
  tests/Unit/Http/Controllers/UserCrudController.php
  tests/Unit/Http/CrudControllerTest.php
  tests/Unit/Models/ModelWithoutCrudTrait.php
Labels: Priority: MUST

#4845 use field validation directly in getting started tutorial
  src/resources/views/base/inc/getting_started.blade.php
Labels: Priority: MUST

#4849 AuthenticatesSessions contract doesn't exist in L8
  src/app/Http/Middleware/AuthenticateSession.php
  src/app/Http/Middleware/AuthenticateSessionL9.php
Labels: Bug, Priority: MUST

#4529 remove anonymous function
  src/app/Library/CrudPanel/Traits/Validation.php
  tests/Unit/CrudPanel/CrudPanelValidationTest.php
  tests/Unit/Http/Controllers/UserCrudController.php
  tests/Unit/Http/Requests/UserRequest.php
  tests81/Unit/CrudPanel/CrudPanelFieldsTest.php
Labels: Priority: MUST, Priority: SHOULD, Minor Bug

#4822 Fix CrudFilter initialization from static class method.
  src/app/Library/CrudPanel/CrudFilter.php
Labels: Bug, Priority: MUST

#4820 [Bug] Can't change column key fluently
  src/app/Library/CrudPanel/CrudColumn.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
Labels: Bug, Priority: MUST

#4852 use temporary disk in column too
  src/resources/views/crud/columns/upload_multiple.blade.php
Labels: Bug
