Repository Laravel-Backpack/CRUD, pull requests merged in 2022-03, with the labels that each got.

#4211 [Bug] Dependencies in repeatable containers
  src/helpers.php
  tests/Unit/CrudPanel/HelpersTest.php
Labels: Bug

#4242 #4200 add cropend event to image fields
  src/resources/views/crud/fields/base64_image.blade.php
  src/resources/views/crud/fields/image.blade.php
Labels: Bug

#4255 fix #4188 - bulk actions in safari
  src/resources/views/crud/columns/inc/bulk_actions_checkbox.blade.php
Labels: Priority: MUST

#4259 use crud query instead of model in getEntry()
  src/app/Library/CrudPanel/Traits/Read.php
Labels: Bug, Priority: SHOULD

#4260 add default upload styles to upload_multiple
  src/resources/views/crud/fields/upload_multiple.blade.php
Labels: Bug

#4268 Validate field name attribute
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: Minor Bug

#4221 fix required fields (asterisc) inside repeatable
  src/app/Library/CrudPanel/Traits/Validation.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
Labels: Bug, Priority: MUST

#4291 Use e() when dumping the exception message on error pages
  src/resources/error_views/400.blade.php
  src/resources/error_views/401.blade.php
  src/resources/error_views/403.blade.php
  src/resources/error_views/404.blade.php
  src/resources/error_views/405.blade.php
  src/resources/error_views/408.blade.php
  src/resources/error_views/429.blade.php
  src/resources/error_views/500.blade.php
  src/resources/error_views/503.blade.php
Labels: Priority: MUST

#4292 add viewNamespace alias to array definition for consistency
  src/app/Library/CrudPanel/CrudFilter.php
Labels: Feature

#4298 Add fix command in 5.x
  src/BackpackServiceProvider.php
  src/app/Console/Commands/Fix.php
Labels: Priority: MUST

#4299 Add fix command in 4.1
  src/BackpackServiceProvider.php
  src/app/Console/Commands/Fix.php
Labels: Priority: MUST

#4300 Add fix command in 4.0
  src/BackpackServiceProvider.php
  src/app/Console/Commands/Fix.php
  src/resources/error_views/400.blade.php
Labels: Priority: MUST
