Repository Laravel-Backpack/CRUD, pull requests merged in 2022-10, with the labels that each got.

#4649 Cache DB schema info to avoid huge DB table info calls
  src/BackpackServiceProvider.php
  src/app/Library/CrudPanel/Traits/AutoSet.php
  src/app/Library/Database/DatabaseSchema.php
  src/app/Library/Database/TableSchema.php
  src/app/Models/Traits/HasRelationshipFields.php
Labels: Bug, Priority: MUST

#4645 Add List order support for translatable models
  src/app/Library/CrudPanel/Traits/Search.php
  src/app/Models/Traits/SpatieTranslatable/HasTranslations.php
Labels: Bug, Priority: MUST

#4687 Render errors from "any" error bag that is sent on the CrudRequest
  src/resources/views/crud/form_content.blade.php
  src/resources/views/crud/inc/grouped_errors.blade.php
  src/resources/views/crud/inc/show_tabbed_fields.blade.php
Labels: Priority: MUST, Minor Bug

#4670 Validates user connection on backpack install
  src/app/Console/Commands/Install.php
Labels: Priority: MUST, Priority: SHOULD

#4713 check if pro is enable before using table field
  src/app/Library/CrudPanel/Traits/AutoSet.php
Labels: Priority: MUST, Minor Bug

#4579 Morphto v2 - with ajax support
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/Input.php
  src/app/Library/CrudPanel/Traits/MorphRelationships.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/app/Library/CrudPanel/Traits/Validation.php
  src/resources/views/crud/form_content.blade.php
Labels: Priority: MUST

#4701 Avoid bulk checkbox to pollute the first column in exported files
  src/resources/views/crud/inc/export_buttons.blade.php
Labels: Bug

#4678 PHP Enums support
  composer.json
  phpunit.xml
  src/resources/views/crud/columns/enum.blade.php
  src/resources/views/crud/fields/enum.blade.php
  tests/config/database/migrations/2017_09_06_000000_create_articles_table.php
  tests81/Unit/CrudPanel/CrudPanelUpdateTest.php
  tests81/Unit/Models/ArticleWithEnum.php
  tests81/Unit/Models/Enums/StateEnum.php
  tests81/Unit/Models/Enums/StatusEnum.php
  tests81/Unit/Models/Enums/StyleEnum.php
Labels: Priority: SHOULD

#4719 fix 1px bump on select2
  src/public/packages/backpack/base/css/blue-bundle.css
  src/public/packages/backpack/base/css/bundle.css
  src/resources/assets/scss/customs/_form.scss
Labels: Priority: MUST, Minor Bug

#4721 [HOT-FIX] use table name when selecting the column
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Bug

#4728 Fix attribute infering
  src/app/Library/CrudPanel/Traits/Relationships.php
Labels: Priority: MUST

#4684 google map field v2
  src/resources/lang/en/crud.php
Labels: Priority: MUST

#4729 check if property is empty in request
  src/app/Http/Controllers/Operations/ListOperation.php
Labels: Bug, Priority: MUST

#4736 [Bugfix] Cast value to int for switch field
  src/resources/views/crud/fields/switch.blade.php
Labels: Priority: MUST, Minor Bug

#4742 Add fileName parameter to uploadFileToDisk function
  src/app/Models/Traits/HasUploadFields.php
Labels: Priority: SHOULD

#4743 add null checking for options when it's a string in a morphMap
  src/app/Library/CrudPanel/Traits/MorphRelationships.php
Labels: Bug, Priority: MUST

#4754 QueryBuilder automatically add table prefix
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Bug
