Repository Laravel-Backpack/CRUD, pull requests merged in 2022-11, with the labels that each got.

#3645 [Feature] Logout other devices upon password change
  src/app/Http/Controllers/Auth/ResetPasswordController.php
  src/app/Http/Controllers/MyAccountController.php
  src/app/Http/Middleware/AuthenticateSession.php
  src/config/backpack/base.php
Labels: Priority: SHOULD

#4741 use reflection to work with php enum classes
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/resources/views/crud/fields/enum.blade.php
Labels: Priority: MUST, Minor Bug

#4767 Replace likely typo getCleanFields() with getCleanStateFields(); fixes #4765
  src/app/Library/CrudPanel/Traits/Fields.php
Labels: Bug, Priority: MUST

#4714 make distinction between inline inputs and main form inputs
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Bug, Priority: MUST

#2340 [Bug Fix] Save actions inside dropdown don't trigger HTML5 Validation
  src/resources/views/crud/form_content.blade.php
  src/resources/views/crud/inc/form_save_buttons.blade.php
Labels: Bug, Priority: SHOULD

#4770 Merge column and field guess functions
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: Priority: MUST

#4788 Don't exclude raw expression columns
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Bug, Priority: MUST

#4784 Fix alias name for msslq
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Bug, Priority: MUST

#4783 Add password field support for default value
  src/resources/views/crud/fields/password.blade.php
Labels: Priority: COULD

#4782 add `backpack:publish-assets` command that publishes CSS and JS assets
  src/BackpackServiceProvider.php
  src/app/Console/Commands/PublishAssets.php
Labels: Priority: MUST

#4795 fix save actions
  src/resources/views/crud/inc/form_save_buttons.blade.php
Labels: Priority: MUST
