Repository Laravel-Backpack/CRUD, pull requests merged in 2022-07, with the labels that each got.

#4465 Fixed Noty CSS on blue bundle
  src/public/packages/backpack/base/css/blue-bundle.css
  src/resources/assets/scss/blue-bundle.scss
Labels: Bug, Priority: MUST

#4455 JS fields - Added `parent` on subfields instead of `subfieldHolder`
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: COULD

#4490 Fixed icons and alignment on non responsive datatable
  src/public/packages/backpack/base/css/blue-bundle.css
  src/public/packages/backpack/base/css/bundle.css
  src/resources/assets/scss/customs/_list.scss
Labels: Bug

#4504 Fluent columns, add key() function to properly allow overrides
  src/app/Library/CrudPanel/CrudColumn.php
Labels: Priority: MUST, Minor Bug

#4505 add invokable support to strippedRequest
  src/app/Library/CrudPanel/Traits/Fields.php
  src/config/backpack/operations/create.php
  src/config/backpack/operations/update.php
Labels: Bug, Feature, Priority: MUST

#4514 check if method exists before calling
  src/app/Library/CrudPanel/Traits/Update.php
Labels: Bug, Priority: MUST

#4512 [Bug] Fix column attribute for filters
  src/app/Library/CrudPanel/Traits/Columns.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
Labels: Bug, Priority: MUST

#4458 Move DataTable reordering in its own function (for server-side exports to use it)
  src/app/Http/Controllers/Operations/ListOperation.php
  src/app/Library/CrudPanel/Traits/Search.php
  src/resources/views/crud/list.blade.php
Labels: Priority: SHOULD, Priority: COULD

#4463 Added switch field
  src/resources/views/crud/fields/switch.blade.php
Labels: Feature

#4520 Load view namespaces into crud instead of config
  src/app/Library/CrudPanel/CrudButton.php
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/HasViewNamespaces.php
  src/app/Library/CrudPanel/Traits/Search.php
  src/app/Library/CrudPanel/Traits/Views.php
  src/app/Library/Widget.php
  src/resources/views/crud/show.blade.php
Labels: Priority: MUST

#4493 Fix `mb_strwidth()` Passing null to parameter 1 is deprecated #4492
  src/helpers.php
  src/resources/views/crud/columns/email.blade.php
  src/resources/views/crud/columns/model_function.blade.php
  src/resources/views/crud/columns/model_function_attribute.blade.php
  src/resources/views/crud/columns/phone.blade.php
  src/resources/views/crud/columns/row_number.blade.php
  src/resources/views/crud/columns/select.blade.php
  src/resources/views/crud/columns/select_multiple.blade.php
  src/resources/views/crud/columns/text.blade.php
Labels: Bug, Priority: MUST

#4533 HOT FIX: remove php 8 code from function constructor
  src/app/Library/CrudPanel/Traits/HasViewNamespaces.php
Labels: Bug, Priority: MUST

#4532 Add Laravel 9 to testing matrix
  .github/workflows/testing.yml
  composer.json
Labels: Priority: MUST

#4540 [BUG] add more checks, change execution order in strippedRequest
  src/app/Library/CrudPanel/Traits/Fields.php
Labels: Bug

#4543 trigger the delete events for each of related deleted model
  src/app/Library/CrudPanel/Traits/Create.php
Labels: Bug
