Repository Laravel-Backpack/CRUD, pull requests merged in 2022-04, with the labels that each got.

#4287 Add fluent methods and macro for field validation
  src/BackpackServiceProvider.php
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/Validation.php
  src/macros.php
  tests/BaseTest.php
Labels: Priority: MUST

#4315 mention pro when view not found for fields as a suggestion
  src/app/Exceptions/BackpackProRequiredException.php
  src/app/Http/Controllers/ChartController.php
  src/app/Http/Controllers/CrudController.php
  src/app/Http/Controllers/Operations/BulkCloneOperation.php
  src/app/Http/Controllers/Operations/BulkDeleteOperation.php
  src/app/Http/Controllers/Operations/CloneOperation.php
  src/app/Http/Controllers/Operations/FetchOperation.php
  src/app/Http/Controllers/Operations/InlineCreateOperation.php
  src/app/Library/CrudPanel/CrudFilter.php
  src/app/Library/CrudPanel/Traits/Read.php
  src/app/Library/CrudPanel/Traits/Views.php
  src/app/Library/Widget.php
  tests/Unit/CrudPanel/CrudPanelReadTest.php
Labels: Priority: MUST, refactoring

#4289 Fix table header when not responsive
  src/public/packages/backpack/base/css/blue-bundle.css
  src/public/packages/backpack/base/css/bundle.css
  src/resources/assets/scss/customs/_list.scss
  src/resources/views/crud/list.blade.php
Labels: Bug, Priority: MUST

#4314 add configurable search operator for ListOperation
  src/app/Library/CrudPanel/Traits/Search.php
  src/config/backpack/operations/list.php
Labels: Minor Bug

#4282 Use Js::from() to create proper JavaScript var
  src/resources/views/base/inc/alerts.blade.php
Labels: Possible Bug

#4321 Fix date_range not being saved when subfield (and any other field with array names)
  src/app/Library/CrudPanel/Traits/FakeFields.php
  src/app/Library/CrudPanel/Traits/Update.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/Models/AccountDetails.php
  tests/Unit/Models/Universe.php
  tests/Unit/Models/User.php
  tests/config/database/migrations/2017_09_08_000001_create_account_details_table.php
  tests/config/database/migrations/2020_03_31_114745_create_pivotable_relations_tables.php
Labels: Priority: MUST

#4313 Fix for translatable models to use the crud query too
  src/app/Library/CrudPanel/Traits/Read.php
Labels: Bug

#4332 Support dot.notation fields in the selectors
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4331 add backpack input identifier to select multiple fields
  src/resources/views/crud/fields/select_from_array.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
Labels: Priority: MUST

#4333 Color picker and summernote editor to trigger the change event
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4335 Wysiwyg editors enable and disable
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4336 all javascript operations working in checkbox and radio
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST
