Repository Laravel-Backpack/CRUD, pull requests merged in 2022-08, with the labels that each got.

#4528 [bug] fix when ConvertEmptyStringsToNull is disabled for M-M relations
  src/app/Library/CrudPanel/Traits/Create.php
Labels: Priority: MUST, Minor Bug

#4559 Improvements on console UI for install command
  src/BackpackServiceProvider.php
  src/app/Console/Commands/Addons/RequireDevTools.php
  src/app/Console/Commands/Addons/RequireEditableColumns.php
  src/app/Console/Commands/Addons/RequirePro.php
  src/app/Console/Commands/Install.php
  src/app/Console/Commands/RequireDevTools.php
  src/app/Console/Commands/Traits/AddonsHelper.php
  src/app/Console/Commands/Traits/PrettyCommandOutput.php
Labels: Priority: MUST

#4577 Show getting started widget on dashboard (on localhost)
  src/config/backpack/base.php
  src/resources/views/base/dashboard.blade.php
  src/resources/views/base/inc/getting_started.blade.php
Labels: Priority: MUST

#4585 remove deprecated strftime() in PHP 8.1
  src/resources/views/crud/fields/datetime.blade.php
Labels: Priority: MUST, Minor Bug

#4586 remove deprecated strftime in 4.1 branch
  src/resources/views/crud/fields/datetime.blade.php
Labels: Priority: MUST, Minor Bug

#4589 use APP_ENV instead of app()->env in show_getting_started
  src/config/backpack/base.php
Labels: Priority: MUST

#4590 Improved UI for both custom route command and add sidebar content command
  src/app/Console/Commands/AddCustomRouteContent.php
  src/app/Console/Commands/AddSidebarContent.php
  src/resources/views/base/inc/getting_started.blade.php
Labels: Priority: MUST

#4592 Improve PHPDoc of CheckIfAdmin middleware
  src/app/Http/Middleware/CheckIfAdmin.php
Labels: refactoring

#4594 Replace HTML comments with Blade comments
  src/resources/views/base/auth/passwords/email.blade.php
  src/resources/views/base/auth/passwords/reset.blade.php
  src/resources/views/base/inc/head.blade.php
  src/resources/views/base/inc/main_header.blade.php
  src/resources/views/base/inc/menu.blade.php
  src/resources/views/base/inc/scripts.blade.php
  src/resources/views/base/inc/sidebar.blade.php
  src/resources/views/base/inc/sidebar_content.blade.php
  src/resources/views/base/inc/topbar_left_content.blade.php
  src/resources/views/base/inc/topbar_right_content.blade.php
  src/resources/views/base/layouts/top_left.blade.php
  src/resources/views/base/widgets/view.blade.php
  src/resources/views/crud/buttons/show.blade.php
  src/resources/views/crud/buttons/update.blade.php
  src/resources/views/crud/columns/multidimensional_array.blade.php
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/checklist.blade.php
  src/resources/views/crud/fields/checklist_dependency.blade.php
  src/resources/views/crud/fields/color.blade.php
  src/resources/views/crud/fields/custom_html.blade.php
  src/resources/views/crud/fields/date.blade.php
  src/resources/views/crud/fields/datetime.blade.php
  src/resources/views/crud/fields/email.blade.php
  src/resources/views/crud/fields/enum.blade.php
  src/resources/views/crud/fields/hidden.blade.php
  src/resources/views/crud/fields/month.blade.php
  src/resources/views/crud/fields/number.blade.php
  src/resources/views/crud/fields/password.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/range.blade.php
  src/resources/views/crud/fields/select.blade.php
  src/resources/views/crud/fields/select_from_array.blade.php
  src/resources/views/crud/fields/select_grouped.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/fields/text.blade.php
  src/resources/views/crud/fields/textarea.blade.php
  src/resources/views/crud/fields/time.blade.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
  src/resources/views/crud/fields/url.blade.php
  src/resources/views/crud/fields/view.blade.php
  src/resources/views/crud/fields/week.blade.php
  src/resources/views/crud/form_content.blade.php
  src/resources/views/crud/inc/filters_navbar.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
  src/resources/views/crud/show.blade.php
Labels: Priority: COULD

#4547 Fix reorder operation - after dropping the item, all items expand
  src/public/packages/nestedSortable/jquery.mjs.nestedSortable2.js
Labels: Priority: SHOULD, Minor Bug

#4557 fix shift select bulk actions
  src/resources/views/crud/columns/inc/bulk_actions_checkbox.blade.php
Labels: Bug, Priority: MUST

#4491 [Feature] Repeatable field focuses on first focusable input
  src/resources/views/crud/form_content.blade.php
Labels: Priority: SHOULD, enhancement

#4548 Fix column key definition
  src/app/Library/CrudPanel/CrudColumn.php
Labels: Priority: MUST, Minor Bug

#4558 fix datatable persistency when manually filtering
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Bug, Priority: MUST

#4556 clear selections not found in filtered results
  src/resources/views/crud/columns/inc/bulk_actions_checkbox.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Bug, Priority: MUST

#4598 CrudFields - Subfields callbacks on the fly
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4609 mention Newsletter and Premium addons in Getting Started widget
  src/resources/views/base/inc/getting_started.blade.php
Labels: Priority: MUST

#4554 [bug] Scoped HasMany relations - incorrect delete entries
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/Models/Transaction.php
  tests/Unit/Models/User.php
  tests/config/database/migrations/2020_03_31_114745_create_pivotable_relations_tables.php
Labels: Bug

#4613 fix str_repeat error
  src/app/Console/Commands/Traits/PrettyCommandOutput.php
Labels: URGENT, Priority: MUST

#4522 Extend config to support custom Vite styles and scripts
  src/config/backpack/base.php
  src/resources/views/base/inc/head.blade.php
  src/resources/views/base/inc/scripts.blade.php
Labels: Priority: SHOULD, Priority: COULD

#4615 Fix select2 input focus & select2 multiple input remove
  src/resources/views/crud/form_content.blade.php
Labels: Priority: MUST

#4616 Add style focus to select2
  src/resources/assets/scss/customs/_form.scss
Labels: Priority: SHOULD, Minor Bug

#4627 remove extra parenthesis from checklist dependency
  src/resources/views/crud/fields/checklist_dependency.blade.php
Labels: Priority: MUST
