Repository Laravel-Backpack/CRUD, pull requests merged in 2022-05, with the labels that each got.

#4342 rename backpack events
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4338 field entity should be false if not otherwise specified
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  tests/Unit/CrudPanel/CrudPanelAutoSetTest.php
  tests/Unit/CrudPanel/CrudPanelFieldsTest.php
  tests/Unit/CrudPanel/CrudPanelReadTest.php
  tests/Unit/CrudPanel/CrudPanelUpdateTest.php
Labels: Bug, Priority: SHOULD

#4354 use closest instead of find
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4220 Always apply field validation, on top of array & formRequest validation
  src/BackpackServiceProvider.php
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
  src/app/Library/CrudPanel/Traits/Validation.php
  src/macros.php
  src/resources/lang/en/crud.php
  tests/BaseTest.php
Labels: Bug, Priority: MUST

#4370 hotfix: arrayed parent names can't be used
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
Labels: Bug

#4390 Check for class instead of value
  src/app/Library/CrudPanel/Traits/Update.php
Labels: Bug, Priority: MUST

#4261 Make uploadMultipleFilesToDisk() work with model events
  src/app/Models/Traits/HasUploadFields.php
Labels: Priority: SHOULD, Minor Bug

#4385 fixes for checklist and date_range fields (arrayed field names)
  src/resources/views/crud/fields/checklist_dependency.blade.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4379 JS library - forced values on `show`, `enable`, `require`, `check`
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: SHOULD

#4399 set locale on entry on operations that need them
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/app/Http/Controllers/Operations/UpdateOperation.php
  src/app/Library/CrudPanel/Traits/Read.php
Labels: Bug, Priority: MUST

#4401 fix (update): dynamically get pivot accessor when saving n-n relations
  src/app/Library/CrudPanel/Traits/Update.php
Labels: Priority: MUST, Minor Bug

#4402 fix infering the connecting key on HasMany relations
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: Bug, Priority: MUST

#4403 Add repeatable support to js library
  src/app/Http/Controllers/Operations/ShowOperation.php
  src/app/Http/Controllers/Operations/UpdateOperation.php
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Read.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/lang/ar/crud.php
  src/resources/lang/fr/base.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST
