Repository Laravel-Backpack/CRUD, pull requests merged in 2022-09, with the labels that each got.

#4625 make fields wrapper optional
  src/resources/views/crud/fields/custom_html.blade.php
  src/resources/views/crud/fields/view.blade.php
Labels: Priority: SHOULD, Minor Bug

#4651 Work around for specific PRO versions
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/HasViewNamespaces.php
Labels: Priority: MUST, Minor Bug

#4643 remove path separator from begin of string
  src/app/Library/CrudPanel/CrudPanel.php
Labels: Priority: SHOULD, Minor Bug

#4664 Add methods into view namespaces to avoid BC
  src/app/Library/CrudPanel/Traits/HasViewNamespaces.php
Labels: Bug, URGENT, Priority: MUST

#4662 Add config for backpack_email_column
  src/config/backpack/base.php
  src/helpers.php
  src/resources/views/base/auth/login.blade.php
  src/resources/views/base/auth/register.blade.php
  src/resources/views/base/my_account.blade.php
Labels: Priority: SHOULD, Minor Bug

#4659 Fix to allow export of input/select
  src/resources/views/crud/inc/export_buttons.blade.php
Labels: Bug, Priority: SHOULD

#4661 Add method to get widget attributes
  src/app/Library/Widget.php
Labels: Priority: SHOULD

#4672 Fix Reorder When Page is RTL
  src/resources/views/crud/reorder.blade.php
Labels: Minor Bug
