Repository Laravel-Backpack/CRUD, pull requests merged in 2022-02, with the labels that each got.

#4129 Make fake fields work when used as subfields
  src/app/Library/CrudPanel/Traits/FakeFields.php
  src/app/Library/CrudPanel/Traits/Input.php
  src/resources/views/crud/fields/select2_grouped.blade.php
  src/resources/views/crud/fields/select_grouped.blade.php
  tests/Unit/CrudPanel/CrudPanelFakeFieldsTest.php
Labels: Priority: MUST

#4139 `old()` does not work in s/s2_multiple
  src/resources/views/crud/fields/select2_multiple.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
Labels: Bug

#3387 ensure table column works with associative arrays too
  src/resources/views/crud/columns/table.blade.php
Labels: Feature, non breaking change, Priority: MUST, Priority: SHOULD, affected-by-open-core-split

#4150 Asterisks for repeatable fields
  src/app/Library/CrudPanel/Traits/Validation.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
  src/resources/views/crud/fields/repeatable.blade.php
  src/resources/views/crud/form_content.blade.php
Labels: Priority: MUST

#3376 Select2 filter fixes
  src/resources/views/crud/filters/date.blade.php
  src/resources/views/crud/filters/date_range.blade.php
  src/resources/views/crud/filters/dropdown.blade.php
  src/resources/views/crud/filters/example.blade.php
  src/resources/views/crud/filters/range.blade.php
  src/resources/views/crud/filters/select2.blade.php
  src/resources/views/crud/filters/select2_ajax.blade.php
  src/resources/views/crud/filters/select2_multiple.blade.php
  src/resources/views/crud/filters/simple.blade.php
  src/resources/views/crud/filters/text.blade.php
  src/resources/views/crud/inc/filters_navbar.blade.php
Labels: Priority: MUST, Priority: SHOULD, Minor Bug, affected-by-open-core-split

#4166 Check for `model` key before it is called
  src/app/Library/CrudPanel/Traits/FakeFields.php
Labels: Bug

#4170 [v5] use a fresh relation instance to create related items
  src/app/Library/CrudPanel/Traits/Create.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
Labels: Bug

#4164 Add support for single-method Laravel Accessors and Mutators
  src/app/Library/CrudPanel/CrudPanel.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Relationships.php
Labels: Feature, Priority: MUST

#4179 fix #4175 - nestedSortable was not working with jQuery UI 1.13+
  src/public/packages/nestedSortable/jquery.mjs.nestedSortable2.js
Labels: Bug, Priority: MUST

#4181 Comparing string classes instead of objects
  src/app/Library/CrudPanel/Traits/Relationships.php
Labels: Bug

#4184 Fix variable name in first view helper.
  src/app/Library/CrudPanel/Traits/Views.php
Labels: Bug

#4186 In show_fields, use `getFirstFieldView()` method
  src/resources/views/crud/inc/show_fields.blade.php
Labels: Priority: SHOULD

#4191 Fix for `address_algolia` field not found
  src/resources/views/crud/fields/address.blade.php
Labels: Bug

#4190 Removed last bits of placeholder
  src/config/backpack/base.php
  src/helpers.php
  src/resources/views/base/inc/menu_user_dropdown.blade.php
Labels: Priority: SHOULD, refactoring

#4189 Removed is countable helper
  src/helpers.php
Labels: Priority: SHOULD, Priority: COULD, refactoring

#4201 add css that forces width on select2 placeholder
  src/resources/views/crud/inc/show_tabbed_fields.blade.php
Labels: Minor Bug

#4205 Delete HasMany subentry when relation column is not nullable
  src/app/Library/CrudPanel/Traits/Create.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
  tests/Unit/Models/PlanetNonNullable.php
  tests/Unit/Models/User.php
  tests/config/database/migrations/2020_03_31_114745_create_pivotable_relations_tables.php
  tests/config/database/seeds/MorphableSeeders.php
Labels: Bug, Priority: MUST

#4231 add select_grouped - fixes #4226
  src/resources/views/crud/fields/select_grouped.blade.php
Labels: Bug
