Repository Laravel-Backpack/CRUD, pull requests merged in 2022-06, with the labels that each got.

#4400 JS library - Changed closure args
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: SHOULD

#4411 Add support for the repeatable field
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4427 CrudField JS API - add triggerChange method
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: SHOULD, Priority: COULD

#4431 Trigger change also for subfields
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4434 return value from jquery input
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Bug

#4439 rename js events
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/checklist.blade.php
  src/resources/views/crud/fields/checklist_dependency.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: MUST

#4312 Add JS library for interacting with fields inside a CRUD form
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/checklist.blade.php
  src/resources/views/crud/fields/checklist_dependency.blade.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/select_from_array.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
  src/resources/views/crud/form_content.blade.php
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Feature, non breaking change, Priority: MUST

#4459 Fix validation when no FormRequest provided
  src/app/Library/CrudPanel/Traits/Validation.php
Labels: Bug, Priority: MUST

#4457 JS fields - `change` consistent return
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: SHOULD

#4359 Related models should have the main entry locale too
  src/app/Library/CrudPanel/Traits/Update.php
Labels: Priority: MUST, Minor Bug

#4462 only add the hidden input in case it doesn't exist
  src/resources/views/crud/fields/checklist_dependency.blade.php
Labels: Bug, Priority: MUST

#4472 Fix entity() attribute guessing for Fluent fields
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/Fields.php
Labels: Bug

#4476 Link to correct version of CoreUI in config
  src/config/backpack/base.php
Labels: Minor Bug
