Repository Laravel-Backpack/CRUD, pull requests merged in 2023-08, with the labels that each got.

#5248 Remove backpack:publish-assets command from v6
  src/BackpackServiceProvider.php
  src/app/Console/Commands/PublishAssets.php
Labels: Priority: SHOULD, todo :spiral_notepad:, Size: XS

#5230 Add missing fallback themes config for list operation
  src/config/backpack/ui.php
Labels: Bug, Priority: MUST, Size: XS

#5242 Make Summernote dropdowns work in Bootstrap 5 & 4
  src/resources/assets/css/common.css
  src/resources/views/crud/fields/summernote.blade.php
Labels: Bug, Priority: MUST, Size: XS

#5262 fix comma delimited fake fields
  src/app/Library/CrudPanel/Traits/FakeFields.php
Labels: Bug

#5270 Add array support to CrudColumn object.
  src/app/Library/CrudPanel/CrudColumn.php
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/Support/MacroableWithAttributes.php
  tests/Unit/CrudPanel/CrudPanelColumnsTest.php
Labels: Bug, Priority: MUST

#5243 Handle uploads inside relationships
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/Uploaders/SingleFile.php
  src/app/Library/Uploaders/Support/Interfaces/UploaderInterface.php
  src/app/Library/Uploaders/Support/RegisterUploadEvents.php
  src/app/Library/Uploaders/Support/Traits/HandleRepeatableUploads.php
  src/app/Library/Uploaders/Uploader.php
Labels: Bug, Priority: MUST

#5275 Fix list view css - wrong first column height
  src/resources/assets/css/common.css
Labels: Bug, Priority: MUST, Size: XS

#5277 Fixed List operation spinner.svg path
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Bug, Priority: MUST, Size: XS

#5279 Improve subfields errors on handling
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/helpers.php
Labels: Priority: SHOULD

#5280 Fix comma separated field names breaking when a space was added
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
Labels: Priority: MUST, Minor Bug

#5286 Crud update cancel button was removed
  src/resources/views/crud/inc/form_save_buttons.blade.php
Labels: Bug

#5276 Added error page translations
  src/resources/lang/en/base.php
  src/resources/lang/pt/base.php
  src/resources/views/ui/errors/400.blade.php
  src/resources/views/ui/errors/401.blade.php
  src/resources/views/ui/errors/403.blade.php
  src/resources/views/ui/errors/404.blade.php
  src/resources/views/ui/errors/405.blade.php
  src/resources/views/ui/errors/408.blade.php
  src/resources/views/ui/errors/429.blade.php
  src/resources/views/ui/errors/4xx.blade.php
  src/resources/views/ui/errors/500.blade.php
  src/resources/views/ui/errors/503.blade.php
  src/resources/views/ui/errors/blank.blade.php
  src/resources/views/ui/errors/layout.blade.php
Labels: Priority: MUST, Size: XS

#5287 Fix: Table modal display the details row icon in the first column.
  src/resources/assets/css/common.css
Labels: Priority: MUST, Minor Bug, Size: XS

#5289 add nested menu dropdowns to crud
  src/app/View/Components/MenuDropdown.php
Labels: Priority: SHOULD

#5301 Add email confirmation
  src/BackpackServiceProvider.php
  src/app/Http/Controllers/Auth/RegisterController.php
  src/app/Http/Controllers/Auth/VerifyEmailController.php
  src/app/Http/Middleware/EnsureEmailVerification.php
  src/app/Http/Requests/EmailVerificationRequest.php
  src/app/Library/Auth/AuthenticatesUsers.php
  src/app/Library/Auth/UserFromCookie.php
  src/config/backpack/base.php
  src/resources/lang/en/base.php
  src/resources/views/ui/errors/layout.blade.php
  src/routes/backpack/base.php
Labels: Priority: MUST
