Repository Laravel-Backpack/CRUD, pull requests merged in 2023-03, with the labels that each got.

#4947 remove DevTools does not support L10 notice in installer
  src/app/Console/Commands/Addons/RequireDevTools.php
Labels: URGENT, Priority: MUST

#4949 [DX] add return types to facade
  src/app/Library/CrudPanel/CrudPanelFacade.php
Labels: Priority: SHOULD

#4967 Fixed: Reorder with uuid primary key
  src/resources/views/crud/reorder.blade.php
Labels: Bug, Priority: MUST

#4984 BUG-FIX: Set limit on select_multiple column
  src/resources/views/crud/columns/select_multiple.blade.php
Labels: Minor Bug

#4993 V6 move UI configs to separate file
  src/BackpackServiceProvider.php
  src/config/backpack/base.php
  src/config/backpack/ui.php
  src/helpers.php
  src/resources/views/crud/columns/date.blade.php
  src/resources/views/crud/columns/datetime.blade.php
Labels: Priority: SHOULD, Priority: COULD

#4813 [Feature Request] Allow delete button on edit page
  src/resources/views/crud/inc/form_save_buttons.blade.php
Labels: Feature, Priority: SHOULD

#4995 Fixed Vite assets loading
  src/config/backpack/base.php
  src/resources/views/base/inc/head.blade.php
  src/resources/views/base/inc/scripts.blade.php
Labels: Bug

#5001 Use backpack/basset instead of digitallyhappy/bassets
  composer.json
Labels: Priority: MUST

#5005 [Feature] Use dropdown for actions column on List operation
  src/config/backpack/operations/list.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/list.blade.php
Labels: Feature
