Repository Laravel-Backpack/CRUD, pull requests merged in 2023-09, with the labels that each got.

#5315 add crudbutton position method
  src/app/Library/CrudPanel/CrudButton.php
  tests/Unit/CrudPanel/CrudPanelButtonsTest.php
Labels: Bug, Priority: SHOULD, Size: XS

#5306 Wrong Bootstrap class override
  src/resources/assets/css/common.css
Labels: Priority: SHOULD, Minor Bug, Size: XS

#5310 Update Vietnamese
  src/resources/lang/vi/base.php
Labels: Priority: SHOULD, enhancement, Size: XS

#4971 Add Livewire widget
  src/resources/views/ui/widgets/livewire.blade.php
Labels: Priority: MUST, Priority: SHOULD, Size: M
