Repository Laravel-Backpack/CRUD, pull requests merged in 2023-02, with the labels that each got.

#4924 Fix `php artisan backpack:version` command for composer2 installations
  src/app/Console/Commands/Version.php
Labels: Minor Bug

#4926 Follow Laravel release schedule
  README.md
Labels: Epic

#4879 Image column support private bucket
  src/resources/views/crud/columns/image.blade.php
Labels: Priority: SHOULD

#4933 [v6] Use basset block directive in FREE fields
  src/resources/views/crud/buttons/delete.blade.php
  src/resources/views/crud/columns/inc/bulk_actions_checkbox.blade.php
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/checklist.blade.php
  src/resources/views/crud/fields/checklist_dependency.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/summernote.blade.php
  src/resources/views/crud/fields/switch.blade.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
Labels: Priority: MUST, Priority: SHOULD

#4943 Fixed widgets scripts basset loading
  src/resources/views/base/widgets/script.blade.php
Labels: Bug
