Repository Laravel-Backpack/CRUD, pull requests merged in 2023-04, with the labels that each got.

#5022 provide a fallback view namespace for themes
  src/ViewNamespaces.php
  src/app/Library/Widget.php
  src/config/backpack/base.php
  src/config/backpack/ui.php
  src/helpers.php
Labels: Priority: MUST

#4983 [BUG-FIX] backpack_form_input() handle multiple inputs
  src/helpers.php
Labels: Bug, Priority: MUST

#5036 [Tabler] V6 mauro
  src/app/Http/Controllers/AdminController.php
  src/config/backpack/operations/create.php
  src/config/backpack/operations/reorder.php
  src/config/backpack/operations/show.php
  src/config/backpack/operations/update.php
  src/resources/assets/css/common.css
Labels: Priority: MUST

#5032 Split validation merge process into a new function
  src/app/Library/CrudPanel/Traits/Validation.php
  src/resources/views/crud/fields/upload_multiple.blade.php
Labels: Priority: SHOULD

#4899 Cursor pointer for clickable elements
  src/resources/assets/scss/customs/_form.scss
Labels: Priority: SHOULD, Priority: COULD

#5042 added 2 missing translation for romanian language
  src/resources/lang/ro/crud.php
Labels: Priority: MUST

#5041 [Bug] Actions Dropdown changes back to line buttons after editable switch is toggled
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/list.blade.php
Labels: Bug

#4988 Add `withFiles()` functionality to CRUD fields
  src/BackpackServiceProvider.php
  src/app/Library/CrudPanel/CrudColumn.php
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/Support/MacroableWithAttributes.php
  src/app/Library/Uploaders/MultipleFiles.php
  src/app/Library/Uploaders/SingleBase64Image.php
  src/app/Library/Uploaders/SingleFile.php
  src/app/Library/Uploaders/Support/FileNameGenerator.php
  src/app/Library/Uploaders/Support/Interfaces/FileNameGeneratorInterface.php
  src/app/Library/Uploaders/Support/Interfaces/UploaderInterface.php
  src/app/Library/Uploaders/Support/RegisterUploadEvents.php
  src/app/Library/Uploaders/Support/Traits/HandleFileNaming.php
  src/app/Library/Uploaders/Support/Traits/HandleRepeatableUploads.php
  src/app/Library/Uploaders/Support/UploadersRepository.php
  src/app/Library/Uploaders/Uploader.php
  src/config/backpack/crud.php
  src/macros.php
  src/resources/views/crud/fields/upload.blade.php
  src/resources/views/crud/fields/upload_multiple.blade.php
Labels: Priority: MUST

#5043 [Feature][WIP] Show Operation with Tabs
  src/app/Library/CrudPanel/Traits/Tabs.php
  src/config/backpack/operations/show.php
  src/resources/views/crud/inc/show_tabbed_fields.blade.php
  src/resources/views/crud/inc/show_tabbed_table.blade.php
  src/resources/views/crud/inc/show_table.blade.php
  src/resources/views/crud/show.blade.php
Labels: Feature, Priority: MUST
