Repository Laravel-Backpack/CRUD, pull requests merged in 2023-10, with the labels that each got.

#5340 Run CI tests on PHP 8.3
  .github/workflows/testing.yml
Labels: Priority: SHOULD

#5006 Fix subfields check in Update operation
  src/app/Library/CrudPanel/Traits/Update.php
Labels: Bug, Priority: MUST

#5335 [Feature] Custom access closures
  src/app/Library/CrudPanel/Traits/Access.php
  src/resources/views/crud/buttons/delete.blade.php
  src/resources/views/crud/buttons/quick.blade.php
  src/resources/views/crud/buttons/show.blade.php
  src/resources/views/crud/buttons/update.blade.php
Labels: Feature, Priority: SHOULD, Size: S

#5082 fix: deprecation on dynamic property (PHP82)
  src/app/Http/Controllers/Auth/LoginController.php
  src/app/Http/Controllers/Auth/RegisterController.php
  src/app/Http/Controllers/Auth/ResetPasswordController.php
Labels: Priority: SHOULD
