Repository Laravel-Backpack/CRUD, pull requests merged in 2023-01, with the labels that each got.

#4881 fix main application tests
  src/BackpackServiceProvider.php
  tests/BaseTest.php
Labels: Bug

#4888 Display PRO version when available in `backpack:version` command
  src/app/Console/Commands/Version.php
Labels: Priority: SHOULD

#4846 Deprecation notice on passing null to str_replace
  src/app/Http/Controllers/CrudController.php
Labels: Priority: SHOULD, Priority: COULD

#4408 Add input field prefix & suffix where possible
  src/resources/views/crud/fields/color.blade.php
  src/resources/views/crud/fields/date.blade.php
  src/resources/views/crud/fields/datetime.blade.php
  src/resources/views/crud/fields/email.blade.php
  src/resources/views/crud/fields/month.blade.php
  src/resources/views/crud/fields/password.blade.php
  src/resources/views/crud/fields/select.blade.php
  src/resources/views/crud/fields/select_grouped.blade.php
  src/resources/views/crud/fields/time.blade.php
  src/resources/views/crud/fields/url.blade.php
  src/resources/views/crud/fields/week.blade.php
Labels: Priority: SHOULD, next-version

#4911 fix newQueryWithoutScopes() error
  src/app/Library/CrudPanel/Traits/Query.php
Labels: Bug
