Repository Laravel-Backpack/CRUD, pull requests merged in 2023-06, with the labels that each got.

#5089 Trigger events on the input instead of the jQuery wrapper
  src/resources/views/crud/inc/form_fields_script.blade.php
Labels: Priority: SHOULD, Priority: COULD

#4986 Fix for Laravel 10 new password_reset_tokens table
  src/BackpackServiceProvider.php
Labels: Bug, Priority: MUST

#5086 Fix uploaders lifecycle for repeatable uploaders
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/Support/MacroableWithAttributes.php
  src/app/Library/Uploaders/Support/RegisterUploadEvents.php
  src/macros.php
Labels: Priority: MUST

#4819 CrudButton does not persist in CrudPanel object as columns and fields.
  src/app/Library/CrudPanel/CrudButton.php
  src/app/Library/CrudPanel/Traits/Buttons.php
  tests/Unit/CrudPanel/CrudPanelButtonsTest.php
Labels: Bug, Priority: MUST, Priority: SHOULD

#5109 Fix Custom Validation Rules to validate repeatable fields
  src/app/Library/Validation/Rules/ValidFileArray.php
Labels: Priority: MUST

#5118 CRUD buttons can now pass parameters to views
  src/app/Library/CrudPanel/CrudButton.php
  src/resources/views/crud/buttons/quick.blade.php
  tests/Unit/CrudPanel/CrudPanelButtonsTest.php
Labels: Priority: SHOULD

#4481 [v6] Enhance save action return type
  src/app/Http/Controllers/Operations/UpdateOperation.php
  src/app/Library/CrudPanel/Traits/SaveActions.php
Labels: breaking change, Priority: SHOULD, enhancement, next-version

#4931 added bp-section in HTML for easier CSS targeting
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/details_row.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
  src/resources/views/crud/inc/form_page.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
  src/resources/views/crud/show.blade.php
Labels: Priority: SHOULD, Priority: COULD

#5144 Publish tabler config on backpack install
  src/app/Console/Commands/Install.php
Labels: Priority: MUST

#5135 [v6][Feature] View components for menus
  src/BackpackServiceProvider.php
  src/app/View/Components/MenuDropdown.php
  src/app/View/Components/MenuDropdownItem.php
  src/app/View/Components/MenuItem.php
  src/app/View/Components/MenuSeparator.php
  src/resources/views/ui/components/menu-dropdown-item.blade.php
  src/resources/views/ui/components/menu-dropdown.blade.php
  src/resources/views/ui/components/menu-item.blade.php
  src/resources/views/ui/components/menu-separator.blade.php
Labels: Priority: MUST, Priority: SHOULD, Size: M

#5148 Provide a ThemeServiceProvider for themes
  src/ThemeServiceProvider.php
Labels: Priority: MUST, Priority: SHOULD

#5151 Cache gravatar before showing it
  src/helpers.php
Labels: Priority: MUST, Priority: SHOULD, Size: S

#5152 Add dropdown header component
  src/app/View/Components/MenuDropdownHeader.php
  src/resources/views/ui/components/menu-dropdown-header.blade.php
Labels: Priority: MUST, Priority: SHOULD
