Repository Laravel-Backpack/CRUD, pull requests merged in 2023-07, with the labels that each got.

#5153 Change v6 install command - add theme chooser and make `coreuiv2` the default theme
  src/BackpackServiceProvider.php
  src/app/Console/Commands/Install.php
  src/app/Console/Commands/Themes/InstallsTheme.php
  src/app/Console/Commands/Themes/RequireThemeCoreuiv2.php
  src/app/Console/Commands/Themes/RequireThemeCoreuiv4.php
  src/app/Console/Commands/Themes/RequireThemeTabler.php
  src/config/backpack/ui.php
Labels: Priority: MUST

#5174 dont use layout if theme does not provide it
  src/resources/views/ui/errors/layout.blade.php
Labels: Bug, Priority: MUST

#5173 Make uploaders aware of fake fields
  src/app/Library/Uploaders/MultipleFiles.php
  src/app/Library/Uploaders/SingleBase64Image.php
  src/app/Library/Uploaders/SingleFile.php
  src/app/Library/Uploaders/Support/Interfaces/UploaderInterface.php
  src/app/Library/Uploaders/Uploader.php
Labels: Bug, Priority: MUST

#5177 fix tabs in show operation
  src/resources/views/crud/inc/show_tabbed_table.blade.php
Labels: Bug, Priority: MUST

#5171 Allow menu dropdown component to be open by default
  src/app/View/Components/MenuDropdown.php
  src/resources/views/ui/components/menu-dropdown.blade.php
Labels: Feature, Priority: SHOULD, Priority: COULD, Size: XS

#5190 Fix theme config publishing
  src/app/Console/Commands/Themes/InstallsTheme.php
  src/app/Console/Commands/Themes/RequireThemeCoreuiv2.php
  src/app/Console/Commands/Themes/RequireThemeCoreuiv4.php
  src/app/Console/Commands/Themes/RequireThemeTabler.php
Labels: Bug, Priority: MUST

#5179 Fix upload column url generation
  src/resources/views/crud/columns/upload.blade.php
Labels: Bug, Priority: MUST

#5192 Avoid double json encode the fake fields in uploaders
  src/app/Library/Uploaders/Uploader.php
Labels: Bug

#5195 Account for empty fake container
  src/app/Library/Uploaders/Uploader.php
Labels: Bug

#5198 Major tabler fixes
  src/resources/assets/css/common.css
  src/resources/views/crud/buttons/create.blade.php
  src/resources/views/crud/buttons/delete.blade.php
  src/resources/views/crud/buttons/reorder.blade.php
  src/resources/views/crud/buttons/show.blade.php
  src/resources/views/crud/buttons/update.blade.php
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/inc/form_page.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
  src/resources/views/crud/show.blade.php
Labels: Priority: MUST

#5213 remove phpunit 9 from test and coverage actions
  .github/workflows/coverage.yml
  .github/workflows/testing.yml
Labels: Priority: SHOULD

#5218 fix upload multiple uploader
  src/app/Http/Controllers/Operations/ReorderOperation.php
  src/app/Http/Requests/CrudRequest.php
  src/app/Library/Uploaders/MultipleFiles.php
Labels: Bug

#5231 Fix bad way of using vite
  src/config/backpack/ui.php
Labels: Bug

#5233 Fix upload return path in repeatable uploaders
  src/app/Library/Uploaders/Support/Traits/HandleRepeatableUploads.php
Labels: Bug

#5236 Fix translatable uploads
  src/app/Library/Uploaders/Support/RegisterUploadEvents.php
  src/app/Library/Uploaders/Uploader.php
Labels: Bug

#5237 throw http errors in custom exceptions to render the error views
  src/app/Exceptions/AccessDeniedException.php
  src/app/Exceptions/BackpackProRequiredException.php
Labels: Priority: MUST, Priority: SHOULD, Size: XS

#5238 make tabler the default theme
  src/app/Console/Commands/Install.php
  src/app/Console/Commands/Themes/RequireThemeCoreuiv2.php
  src/app/Console/Commands/Themes/RequireThemeCoreuiv4.php
  src/app/Console/Commands/Themes/RequireThemeTabler.php
Labels: Priority: MUST, Size: XS

#5239 adds a card wrapping the error message
  src/resources/views/ui/errors/layout.blade.php
Labels: Bug

#5244 Load directives after resolving
  src/BackpackServiceProvider.php
Labels: Bug
