Repository Laravel-Backpack/CRUD, pull requests merged in 2023-05, with the labels that each got.

#5056 remove the tabler theme as dependency (aka make unit tests run again)
  composer.json
  src/app/Console/Commands/Install.php
Labels: Priority: MUST

#5049 [V6] Small adjustments on fields
  src/resources/views/crud/fields/switch.blade.php
  src/resources/views/crud/inc/datatables_logic.blade.php
Labels: Priority: MUST

#5038 Uploads validation rules
  phpunit.xml
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Validation.php
  src/app/Library/Validation/Rules/BackpackCustomRule.php
  src/app/Library/Validation/Rules/Support/HasFiles.php
  src/app/Library/Validation/Rules/ValidFileArray.php
  src/app/Library/Validation/Rules/ValidUpload.php
  src/app/Library/Validation/Rules/ValidUploadMultiple.php
  tests/Unit/CrudPanel/CrudPanelValidationTest.php
Labels: Priority: SHOULD

#5061 [v6] UI fallback for views too
  src/BackpackServiceProvider.php
  src/helpers.php
  src/resources/views/ui/inc/menu_items.blade.php
Labels: Priority: MUST

#5063 [Feature Request][v6] Customizable CSS classes for tables
  src/resources/views/crud/list.blade.php
Labels: Feature

#5065 [v6][Bug] Empty ListOperation shows only one small cell in row
  src/resources/assets/css/common.css
Labels: Bug, Minor Bug

#5068 [v6] Last styling pass through tabler theme
  src/resources/views/crud/create.blade.php
  src/resources/views/crud/edit.blade.php
  src/resources/views/crud/fields/checkbox.blade.php
  src/resources/views/crud/fields/color.blade.php
  src/resources/views/crud/fields/date.blade.php
  src/resources/views/crud/fields/datetime.blade.php
  src/resources/views/crud/fields/email.blade.php
  src/resources/views/crud/fields/month.blade.php
  src/resources/views/crud/fields/password.blade.php
  src/resources/views/crud/fields/radio.blade.php
  src/resources/views/crud/fields/range.blade.php
  src/resources/views/crud/fields/select.blade.php
  src/resources/views/crud/fields/select_grouped.blade.php
  src/resources/views/crud/fields/time.blade.php
  src/resources/views/crud/fields/url.blade.php
  src/resources/views/crud/fields/week.blade.php
  src/resources/views/crud/list.blade.php
  src/resources/views/crud/reorder.blade.php
  src/resources/views/crud/show.blade.php
Labels: Bug

#5070 Add attribute to validation array
  src/app/Library/CrudPanel/Traits/Validation.php
Labels: Priority: MUST, Priority: SHOULD

#5075 [Feature Request][v6] Move script file to CRUD for cross-theme use
  src/resources/assets/js/common.js
  src/resources/views/ui/inc/scripts.blade.php
  src/resources/views/ui/inc/styles.blade.php
Labels: Feature, Priority: MUST

#5080 [v6 - BC] Remove support for arrays in field names
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/Traits/AutoSet.php
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Fields.php
  src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/resources/views/crud/fields/inc/wrapper_start.blade.php
  tests/Unit/CrudPanel/CrudPanelCreateTest.php
Labels: Priority: MUST

#5083 Pixel perfect Navbar filters
  src/resources/assets/css/common.css
  src/resources/assets/js/common.js
Labels: needs-more-info

#5066 Remove entry from validator constructor
  src/app/Library/Uploaders/Support/RegisterUploadEvents.php
  src/app/Library/Validation/Rules/BackpackCustomRule.php
  src/app/Library/Validation/Rules/ValidUpload.php
  src/app/Library/Validation/Rules/ValidUploadMultiple.php
Labels: Priority: MUST
