Repository Laravel-Backpack/CRUD, pull requests merged in 2024-01, with the labels that each got.

#5422 Add workaround for quick button inconsistency
  src/app/Http/Controllers/Operations/Concerns/HasForm.php
  src/resources/views/crud/buttons/quick.blade.php
Labels: Priority: MUST, Minor Bug

#5327 Added bootstrap5 class form-select
  src/resources/views/crud/fields/enum.blade.php
  src/resources/views/crud/fields/select.blade.php
  src/resources/views/crud/fields/select_from_array.blade.php
  src/resources/views/crud/fields/select_grouped.blade.php
  src/resources/views/crud/fields/select_multiple.blade.php
Labels: Priority: MUST, Minor Bug

#5389 Don't call controller constructors on route setup
  src/app/Http/Controllers/CrudController.php
  src/app/Library/Attributes/DeprecatedIgnoreOnRuntime.php
  src/app/Library/CrudPanel/CrudRouter.php
  src/macros.php
Labels: Priority: SHOULD, Minor Bug

#5403 Use db transactions in create and update operations
  src/app/Library/CrudPanel/Traits/Create.php
  src/app/Library/CrudPanel/Traits/Update.php
  src/config/backpack/base.php
Labels: Priority: MUST
