Repository Laravel-Backpack/CRUD, pull requests merged in 2024-12, with the labels that each got.

#5725 Clean up uploaders
  src/app/Library/Uploaders/MultipleFiles.php
  src/app/Library/Uploaders/SingleBase64Image.php
  src/app/Library/Uploaders/SingleFile.php
  src/app/Library/Uploaders/Support/Interfaces/UploaderInterface.php
  src/app/Library/Uploaders/Support/Traits/HandleRepeatableUploads.php
  src/app/Library/Uploaders/Uploader.php
  src/resources/views/crud/fields/summernote.blade.php
  tests/config/Uploads/assets/avatar7.jpg
  tests/config/Uploads/assets/pic7.jpg
  tests/config/database/migrations/2024_02_15_125654_create_uploaders_table.php
Labels: Priority: MUST, v7

#5713 allow datatable url configuration
  src/app/Http/Controllers/Operations/ListOperation.php
  src/resources/views/crud/inc/datatables_logic.blade.php
  src/resources/views/crud/inc/filters_navbar.blade.php
Labels: v7

#5732 Run CI tests on PHP 8.4 and fix deprecations
  .github/workflows/testing.yml
  src/app/Console/Commands/Traits/PrettyCommandOutput.php
  src/app/Library/Auth/PasswordBroker.php
  src/app/Library/Database/DatabaseSchema.php
Labels: Priority: SHOULD, enhancement
