Repository Laravel-Backpack/CRUD, pull requests merged in 2024-07, with the labels that each got.

#5560 fix warn before leaving - remove backpack dynamic inputs from serialization
  src/config/backpack/operations/create.php
  src/resources/views/crud/form_content.blade.php
Labels: Bug, Priority: MUST

#5562 make checklist options consistent with other relationship fields
  src/resources/views/crud/fields/checklist.blade.php
Labels: Priority: SHOULD, enhancement, Size: XS

#5552 Add header metas publish command
  src/BackpackServiceProvider.php
  src/app/Console/Commands/PublishHeaderMetas.php
  src/public/android-chrome-192x192.png
  src/public/android-chrome-512x512.png
  src/public/apple-touch-icon.png
  src/public/favicon-16x16.png
  src/public/favicon-32x32.png
  src/public/favicon.ico
  src/public/mstile-144x144.png
  src/public/mstile-150x150.png
  src/public/mstile-310x150.png
  src/public/mstile-310x310.png
  src/public/mstile-70x70.png
  src/public/safari-pinned-tab.svg
  src/resources/stubs/browserconfig.stub
  src/resources/stubs/header_metas.stub
  src/resources/stubs/manifest.stub
Labels: Feature

#5561 navigate to tab when auto-focusing
  src/resources/views/crud/form_content.blade.php
Labels: Bug, Priority: MUST

#5559 Add all select option on checklist field
  src/resources/lang/en/crud.php
  src/resources/views/crud/fields/checklist.blade.php
Labels: Feature, Priority: SHOULD

#5502 Update radio.blade.php
  src/resources/views/crud/fields/radio.blade.php
Labels: Possible Bug, Size: XS

#5342 use upsert instead of 2 queries per row
  src/app/Library/CrudPanel/Traits/Reorder.php
Labels: Priority: SHOULD, Minor Bug

#2951 Add fluent field group
  src/app/Library/CrudPanel/CrudField.php
  src/app/Library/CrudPanel/CrudObjectGroup.php
  src/app/Library/CrudPanel/CrudPanel.php
  tests/Unit/CrudPanel/CrudPanelObjectGroupTest.php
Labels: Feature, non breaking change, Priority: SHOULD, next-version

#5563 Streamline the eager load of relationships in crud objects
  src/app/Library/CrudPanel/Traits/Columns.php
  src/app/Library/CrudPanel/Traits/Read.php
  src/config/backpack/operations/list.php
  src/config/backpack/operations/update.php
Labels: Priority: MUST, Minor Bug

#5581 move the attribute processing to save()
  src/app/Library/CrudPanel/CrudColumn.php
  src/app/Library/CrudPanel/CrudField.php
Labels: Priority: MUST, Minor Bug

#5565 Improve custom route insert command
  src/app/Console/Commands/AddCustomRouteContent.php
  src/routes/backpack/custom.php
Labels: Priority: MUST, Minor Bug

#5576 show selected files in upload multiple field
  src/resources/views/crud/fields/upload_multiple.blade.php
Labels: Priority: MUST, Minor Bug
