Repository Laravel-Backpack/CRUD, pull requests merged in 2024-05, with the labels that each got.

#5504 DB schema was loading ALL tables when not necessary
  src/app/Library/Database/DatabaseSchema.php
  src/app/Library/Database/Table.php
  src/app/Library/Database/TableSchema.php
Labels: Bug, Priority: MUST

#5522 Attribute to set `key` to livewire widget.
  src/resources/views/ui/widgets/livewire.blade.php
Labels: Priority: MUST, enhancement, Size: XS

#5512 [Feature] Add Ajax support to Quick button 😎
  src/resources/lang/en/crud.php
  src/resources/views/crud/buttons/quick.blade.php
Labels: Feature, Priority: MUST
