Repository Laravel-Backpack/CRUD, pull requests merged in 2024-08, with the labels that each got.

#5588 Use CRUD request instead of global request instance
  src/app/Library/CrudPanel/Traits/SaveActions.php
  tests/BaseTestClass.php
  tests/Unit/CrudPanel/CrudPanelFieldsTest.php
  tests/Unit/CrudPanel/CrudPanelSaveActionsTest.php
Labels: Priority: MUST, Minor Bug

#5595 Revert change to fix image href
  src/resources/views/crud/columns/image.blade.php
Labels: needs-more-info, Possible Bug

#5607 Fix mobile icons - folder path
  src/app/Console/Commands/PublishHeaderMetas.php
Labels: Bug, Priority: MUST, Size: XS

#5311 clear code, allow force export overriding
  src/resources/views/crud/inc/export_buttons.blade.php
  src/resources/views/crud/list.blade.php
Labels: Priority: MUST

#5615 Update column priority on move
  src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
Labels: Bug, Priority: MUST

#5639 ensure reordered items match the bindings number
  src/app/Library/CrudPanel/Traits/Reorder.php
Labels: Possible Bug
