Repository Laravel-Backpack/CRUD, pull requests merged in 2025-06, with the labels that each got.

#5810 add Datagrid and Datalist components
  src/BackpackServiceProvider.php
  src/ViewNamespaces.php
  src/app/Library/CrudPanel/CrudButton.php
  src/app/View/Components/Datagrid.php
  src/app/View/Components/Datalist.php
  src/app/View/Components/ShowComponent.php
  src/config/backpack/operations/show.php
  src/resources/assets/css/common.css
  src/resources/views/crud/components/datagrid.blade.php
  src/resources/views/crud/components/datalist.blade.php
  src/resources/views/crud/inc/show_tabbed_table.blade.php
  src/resources/views/crud/inc/show_table.blade.php
Labels: Priority: SHOULD, Size: S, v7

#5815 Added general chip blade file and chip widget
  src/resources/views/crud/chips/general.blade.php
  src/resources/views/crud/widgets/chip.blade.php
Labels: Priority: MUST, Size: M

#5819 Drop support for Laravel 10 and 11
  .github/workflows/testing.yml
  composer.json
Labels: Priority: SHOULD

#5818 Fix hooks at setup level
  src/app/Library/CrudPanel/Hooks/LifecycleHooks.php
Labels: v7
