Repository Laravel-Backpack/CRUD, pull requests merged in 2025-01, with the labels that each got.

#5751 fix switch when no color is given
  src/resources/views/crud/fields/switch.blade.php
Labels: Minor Bug

#5746 Allow returning string on getCurrentEntryId()
  src/app/Library/CrudPanel/Traits/Read.php
Labels: Priority: COULD, Size: XS

#5760 remove class with --var in it
  src/resources/views/crud/fields/switch.blade.php
Labels: Size: XS
